/** Guides med inline vinsøgning (fase 2 — udvid efter GSC-data). */
export const GUIDE_INLINE_SEARCH_SLUGS = new Set([
  "vin-til-flaesketesteg",
  "vin-til-juleaften",
  "vin-til-juleand",
  "bedste-julevin",
  "vin-til-tapas",
  "vin-til-gryderet",
  "vin-til-nytaar-og-nytaarsmenu",
  "rodvin-til-pizza",
  "vin-til-fisk-og-skaldyr",
  "vin-til-grill-og-bbq",
  "den-store-grillguide",
  "vin-til-mexicansk-mad-og-tacos",
  "vin-til-vegetariske-og-veganske-retter",
  "bourgogne-vs-tyskland-pinot-noir",
  "italiensk-vin-jungle",
  "hvidvin-uden-for-de-kendte-rammer",
  "glas-guiden",
  "aabnet-vin-holdbarhed-og-snydetricks",
  "chillable-reds",
  "pet-nat-for-begyndere",
  "vin-til-pizza",
  "bedste-vin-til-gave",
  "bobler-champagne-cava-prosecco-og-cremant",
  "bedste-box-vin",
  "bedste-papvin-under-150-kr",
  "bedste-rose-paa-boks",
  "premium-papvin",
  "okologisk-og-naturvin-paa-boks",
  "papvin-bedst-i-test",
  "bedste-rod-papvin",
  "bedste-hvid-papvin",
  "papvin-tilbud",
  "alkoholfri-riesling",
  "alkoholfri-sauvignon-blanc",
  "alkoholfri-pinot-noir",
  "tor-alkoholfri-hvidvin",
  "alkoholfri-hvidvin-til-skaldyr-og-fisk",
  "alkoholfri-vin-til-tapas",
  "alkoholfri-vin-til-pizza-og-pasta",
  "oddbird-alkoholfri-vin",
  "french-bloom-alkoholfri-vin",
]);

export function guideHasInlineSearch(slug: string): boolean {
  return GUIDE_INLINE_SEARCH_SLUGS.has(slug);
}
