/** Guide → drink-crosslinks (renderes på guide-sider). */
export const GUIDE_DRINK_LINKS: Record<string, readonly { slug: string; label: string }[]> = {
  "vin-i-cocktails-spritz-og-drikke": [
    { slug: "aperol-spritz", label: "Aperol Spritz" },
    { slug: "campari-spritz", label: "Campari Spritz" },
    { slug: "hugo-spritz", label: "Hugo Spritz" },
    { slug: "bicicletta-spritz", label: "Bicicletta Spritz" },
    { slug: "chambord-spritz", label: "Chambord Spritz" },
    { slug: "white-wine-spritzer", label: "White Wine Spritzer" },
    { slug: "vermouth-highball", label: "Vermouth Highball" },
    { slug: "mimosa", label: "Mimosa" },
    { slug: "bellini", label: "Bellini" },
    { slug: "rossini", label: "Rossini" },
    { slug: "negroni-sbagliato", label: "Negroni Sbagliato" },
    { slug: "french-75", label: "French 75" },
    { slug: "sangria-med-rodvin", label: "Sangria med rødvin" },
    { slug: "sangria-blanca", label: "Sangria Blanca" },
    { slug: "rose-sangria", label: "Rosé Sangria" },
    { slug: "tinto-de-verano", label: "Tinto de Verano" },
    { slug: "kalimotxo", label: "Kalimotxo" },
    { slug: "kir", label: "Kir" },
    { slug: "kir-royal", label: "Kir Royal" },
    { slug: "limoncello-spritz", label: "Limoncello Spritz" },
    { slug: "frose", label: "Frosé" },
    { slug: "watermelon-rose-cooler", label: "Watermelon Rosé Cooler" },
    { slug: "sake-cocktail", label: "Sake Cocktail" },
    { slug: "black-velvet", label: "Black Velvet" },
    { slug: "death-in-the-afternoon", label: "Death in the Afternoon" },
  ],
  "bobler-champagne-cava-prosecco-og-cremant": [
    { slug: "mimosa", label: "Mimosa" },
    { slug: "bellini", label: "Bellini" },
    { slug: "rossini", label: "Rossini" },
    { slug: "aperol-spritz", label: "Aperol Spritz" },
    { slug: "campari-spritz", label: "Campari Spritz" },
    { slug: "chambord-spritz", label: "Chambord Spritz" },
    { slug: "hugo-spritz", label: "Hugo Spritz" },
    { slug: "french-75", label: "French 75" },
    { slug: "kir-royal", label: "Kir Royal" },
    { slug: "death-in-the-afternoon", label: "Death in the Afternoon" },
    { slug: "black-velvet", label: "Black Velvet" },
    { slug: "negroni-sbagliato", label: "Negroni Sbagliato" },
    { slug: "pink-sensation", label: "Pink Sensation" },
    { slug: "nytaarsbowle", label: "Nytårsbowle" },
  ],
  "bedste-portvin": [
    { slug: "portvin-tonic", label: "Portvin-tonic (P&T)" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "porto-flip", label: "Porto Flip" },
    { slug: "tawny-sour", label: "Tawny Sour" },
    { slug: "pink-sensation", label: "Pink Sensation" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],
  "hvad-er-portvin": [
    { slug: "portvin-tonic", label: "Portvin-tonic" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "porto-flip", label: "Porto Flip" },
    { slug: "tawny-sour", label: "Tawny Sour" },
  ],
  "sadan-serverer-du-portvin": [
    { slug: "portvin-tonic", label: "Portvin-tonic" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "tawny-sour", label: "Tawny Sour" },
  ],
  "hvid-portvin": [
    { slug: "portvin-tonic", label: "Portvin-tonic (Port & Tonic)" },
    { slug: "port-spritzer", label: "Port Spritzer" },
  ],
  "tawny-portvin": [
    { slug: "tawny-sour", label: "Tawny Sour" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "porto-flip", label: "Porto Flip" },
  ],
  "ruby-portvin": [
    { slug: "porto-flip", label: "Porto Flip" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],
  "douro-dalen-subregioner": [{ slug: "portvin-tonic", label: "Portvin-tonic" }],
  "bedste-julevin": [
    { slug: "roedvinsgloegg", label: "Rødvinsgløgg" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
    { slug: "gluehwein-sour", label: "Glühwein-Sour" },
  ],
  "vin-til-juleaften": [
    { slug: "roedvinsgloegg", label: "Rødvinsgløgg" },
    { slug: "gluehwein-sour", label: "Glühwein-Sour" },
  ],
  "vin-til-nytaar-og-nytaarsmenu": [
    { slug: "nytaarsbowle", label: "Nytårsbowle" },
    { slug: "french-75", label: "French 75" },
    { slug: "kir-royal", label: "Kir Royal" },
    { slug: "death-in-the-afternoon", label: "Death in the Afternoon" },
    { slug: "mimosa", label: "Mimosa" },
    { slug: "negroni-sbagliato", label: "Negroni Sbagliato" },
    { slug: "pink-sensation", label: "Pink Sensation" },
  ],
  "vin-til-sommer": [
    { slug: "hugo-spritz", label: "Hugo Spritz" },
    { slug: "white-wine-spritzer", label: "White Wine Spritzer" },
    { slug: "sangria-med-rodvin", label: "Sangria" },
    { slug: "sangria-blanca", label: "Sangria Blanca" },
    { slug: "rose-sangria", label: "Rosé Sangria" },
    { slug: "tinto-de-verano", label: "Tinto de Verano" },
    { slug: "kalimotxo", label: "Kalimotxo" },
    { slug: "frose", label: "Frosé" },
    { slug: "watermelon-rose-cooler", label: "Watermelon Rosé Cooler" },
    { slug: "rebujito", label: "Rebujito" },
    { slug: "portvin-tonic", label: "Port & Tonic" },
    { slug: "port-spritzer", label: "Port Spritzer" },
    { slug: "vermouth-highball", label: "Vermouth Highball" },
  ],
  "vin-til-brunch": [
    { slug: "mimosa", label: "Mimosa" },
    { slug: "bellini", label: "Bellini" },
    { slug: "rossini", label: "Rossini" },
    { slug: "kir-royal", label: "Kir Royal" },
    { slug: "kir", label: "Kir" },
  ],
  "vin-til-spansk-mad": [
    { slug: "tinto-de-verano", label: "Tinto de Verano" },
    { slug: "kalimotxo", label: "Kalimotxo" },
    { slug: "sangria-med-rodvin", label: "Sangria" },
    { slug: "rebujito", label: "Rebujito" },
  ],
  "hvad-er-sherry-vin": [
    { slug: "rebujito", label: "Rebujito" },
    { slug: "adonis", label: "Adonis" },
    { slug: "bamboo-cocktail", label: "Bamboo Cocktail" },
    { slug: "sherry-cobbler", label: "Sherry Cobbler" },
  ],
  "hvad-er-vermouth": [
    { slug: "adonis", label: "Adonis" },
    { slug: "bamboo-cocktail", label: "Bamboo" },
    { slug: "negroni-sbagliato", label: "Negroni Sbagliato" },
    { slug: "vermouth-highball", label: "Vermouth Highball" },
  ],
  "rosevin-til-mad-og-sommer": [
    { slug: "frose", label: "Frosé" },
    { slug: "rose-sangria", label: "Rosé Sangria" },
    { slug: "watermelon-rose-cooler", label: "Watermelon Rosé Cooler" },
  ],
  "champagne-til-mad": [
    { slug: "french-75", label: "French 75" },
    { slug: "kir-royal", label: "Kir Royal" },
    { slug: "kir", label: "Kir" },
    { slug: "mimosa", label: "Mimosa" },
    { slug: "death-in-the-afternoon", label: "Death in the Afternoon" },
    { slug: "black-velvet", label: "Black Velvet" },
    { slug: "nytaarsbowle", label: "Nytårsbowle" },
  ],
  "vin-til-japansk-mad": [
    { slug: "sake-cocktail", label: "Sake Cocktail" },
  ],
  "vin-til-bourgogne-mad": [
    { slug: "kir", label: "Kir" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
};
