/** Guide → opskrifter med vin i gryden (intern linking). */
export const GUIDE_RECIPE_LINKS: Record<string, readonly { slug: string; label: string }[]> = {
  "vin-til-tapas": [
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "champignons-al-ajillo-med-hvidvin", label: "Champignons al ajillo" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
    { slug: "spansk-koedboller-i-rodvinsauce", label: "Almóndigas i rødvinsauce" },
    { slug: "syltede-roedloeg-med-hvidvin", label: "Syltede rødløg med hvidvin" },
    { slug: "roedvinsgele-til-charcuteri", label: "Rødvinsgelé til charcuteri" },
    { slug: "chimichurri-med-rodvin", label: "Chimichurri med rødvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "hummus-med-hvidvin", label: "Hummus med hvidvin" },
    { slug: "aioli-med-hvidvin", label: "Aioli med hvidvin" },
    { slug: "marinerede-oliven-med-hvidvin", label: "Marinerede oliven med hvidvin" },
    { slug: "kamskjell-med-hvidvin", label: "Kamskjell med hvidvin" },
    { slug: "portvins-fignemarmelade-med-rosmarin", label: "Portvins-fignemarmelade" },
    { slug: "rose-syltede-roedloeg-med-timian", label: "Rosé-syltede rødløg" },
    { slug: "bagt-camembert-med-hvidvin", label: "Bagt camembert med hvidvin" },
    { slug: "manchego-marineret-i-hvidvin", label: "Manchego marineret i hvidvin" },
    { slug: "portvinsglaserede-dadler-med-bacon", label: "Portvinsglaserede dadler" },
    { slug: "kaemperejer-dampet-i-hvidvin", label: "Dampede kæmperejer i hvidvin" },
    { slug: "serrano-med-hvidvinsmarineret-melon", label: "Serrano med hvidvinsmelon" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
    { slug: "portvinssyltede-svampe", label: "Portvinssyltede svampe" },
    { slug: "hvidvins-hvidloegsconfit", label: "Hvidvins-hvidløgsconfit" },
    { slug: "hvidvins-troffelmayo", label: "Hvidvins-trøffelmayo" },
  ],
  "vin-til-gryderet": [
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "boeuf-bourguignon", label: "Boeuf bourguignon" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
    { slug: "braiseret-oksekaebe-med-rodvin", label: "Braiseret oksekaebe" },
    { slug: "svinekaebber-i-rodvinssky", label: "Svinekæber i rødvinssky" },
    { slug: "estofado-oksestuvning-i-rodvin", label: "Estofado" },
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
    { slug: "cassoulet-med-rodvin", label: "Cassoulet med rødvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
    { slug: "feijoada-med-rodvin", label: "Feijoada med rødvin" },
    { slug: "bigos-med-rodvin", label: "Bigos med rødvin" },
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "morbradgryde-med-hvidvin", label: "Mørbradgryde med hvidvin" },
    { slug: "biksemad-med-rodvin", label: "Biksemad med rødvin" },
    { slug: "svinekaeber-i-rodvin-og-moerkt-oel", label: "Svinekæber i rødvin og mørkt øl" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin (Lapin au Vin Blanc)" },
  ],
  "vin-til-suppe": [
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "tomatsuppe-med-hvidvin", label: "Tomatsuppe med hvidvin" },
    { slug: "loegsuppe-med-hvidvin", label: "Løgsuppe med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
    { slug: "caldeirada-med-hvidvin", label: "Caldeirada med hvidvin" },
    { slug: "krebsesuppe-med-hvidvin", label: "Krebsesuppe med hvidvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Jordskokkesuppe med hvidvinsreduktion" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone med hvidvin" },
  ],
  "vin-til-tarteletter": [
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "vol-au-vent-med-hvidvin", label: "Vol-au-vent med hvidvin" },
  ],
  "vin-til-pizza-og-pasta": [
    { slug: "klassisk-lasagne", label: "Klassisk lasagne (vin til glasset)" },
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "pesto-med-hvidvin", label: "Pesto med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "pesto-pasta-hvidvin", label: "Pesto-pasta med hvidvin" },
  ],
  "rodvin-til-pizza": [
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin til pizza" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
  ],
  "vin-til-nytaar-og-nytaarsmenu": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
  ],
  "vin-til-lasagne": [
    { slug: "klassisk-lasagne", label: "Klassisk lasagne (vin til glasset)" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin i kødsovs" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
  ],
  "vin-til-pizza": [
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin til pizza" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "pizza-parmaskinke-og-rucola", label: "Pizza med parma og rucola" },
  ],
  "vin-til-julefrokost": [
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
    { slug: "flaesketesteg-med-rodvin-i-brun-sovs", label: "Flæskesteg med rødvin" },
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
    { slug: "groenlangkaal-med-hvidvin", label: "Grønlangkål med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "risalamande-med-hvidvin", label: "Risalamande med hvidvin" },
    { slug: "aeblekage-hvidvin-karamel", label: "Æblekage med hvidvin-karamel" },
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-fisk-og-skaldyr": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "rodspette-med-hvidvin", label: "Rødspætte med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "fisk-i-hvidvinsauce", label: "Fisk i hvidvinsauce" },
    { slug: "torsk-i-hvidvin", label: "Torsk i hvidvin" },
    { slug: "muslinger-i-hvidvin", label: "Muslinger i hvidvin" },
    { slug: "bouillabaisse-med-hvidvin", label: "Bouillabaisse med hvidvin" },
    { slug: "caldeirada-med-hvidvin", label: "Caldeirada med hvidvin" },
    { slug: "aioli-med-hvidvin", label: "Aioli med hvidvin" },
    { slug: "helleflynder-med-hvidvin", label: "Helleflynder med hvidvin" },
    { slug: "krebsesuppe-med-hvidvin", label: "Krebsesuppe med hvidvin" },
    { slug: "kamskjell-med-hvidvin", label: "Kamskjell med hvidvin" },
    { slug: "oesters-gratineret-med-hvidvin", label: "Østers gratineret med hvidvin" },
    { slug: "lakse-rilette-med-hvidvin", label: "Lakse-rilette med hvidvin" },
    { slug: "blaeksprutteringe-i-hvidvin", label: "Blæksprutteringe i hvidvin" },
    { slug: "pighvar-med-hvidvin-og-vesterhavsost", label: "Pighvar med hvidvin og Vesterhavsost" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
  ],
  "vin-til-boeff": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "balsamico-rodvinsglaserede-skalotteloeg", label: "Balsamico-rødvinsglaserede skalotteløg" },
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Klassisk rødvins-rosmarinmarinade" },
    { slug: "syrlig-rodvin-balsamicomarinade", label: "Syrlig rødvin-balsamicomarinade" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico- og rødvinssirup til steak" },
    { slug: "sauce-bordelaise", label: "Sauce Bordelaise" },
    { slug: "portvins-morkelsauce", label: "Portvins-morkelsauce" },
    { slug: "portvinsglace", label: "Portvinsglace" },
    { slug: "beurre-rouge", label: "Beurre rouge" },
    { slug: "sherry-groen-pebersauce", label: "Sherry- og grøn pebersauce" },
  ],
  "vin-til-oksefilet": [
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "balsamico-rodvinsmarineret-oksemoerbrad", label: "Balsamico-rødvinsmarineret oksemørbrad" },
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce til oksemørbrad" },
  ],
  "vin-til-peberboef": [
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinssauce" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
  ],
  "vin-til-pulled-pork": [
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "svinebryst-braiseret-i-rodvin", label: "Svinebryst braiseret i rødvin" },
  ],
  "vin-til-butter-chicken": [
    { slug: "butter-chicken", label: "Butter chicken (vin til glasset)" },
    { slug: "butter-chicken-med-hvidvin", label: "Butter chicken med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "thai-gron-karry-med-hvidvin", label: "Thai grøn karry med hvidvin" },
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
  ],
  "vin-til-dyreryg": [
    { slug: "fasan-med-rodvin", label: "Fasan med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
  ],
  "vin-til-kalvemoerbrad": [
    { slug: "kalv-i-hvidvinsauce", label: "Kalv i hvidvinsauce" },
    { slug: "blanquette-de-veau-med-hvidvin", label: "Blanquette de veau" },
    { slug: "ossobuco-med-hvidvin", label: "Ossobuco med hvidvin" },
    { slug: "saltimbocca-alla-romana", label: "Saltimbocca alla Romana" },
  ],
  "vin-til-svinemoerbrad": [
    { slug: "svinefilet-i-rodvinssauce", label: "Svinefilet i rødvinssauce" },
    { slug: "karbonader-i-hvidvinsauce", label: "Karbonader i hvidvinsauce" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "morbradgryde-med-paprika-og-hvidvin", label: "Mørbradgryde med paprika og hvidvin" },
    { slug: "hvidvins-sennepsmarinade", label: "Hvidvins-sennepsmarinade" },
  ],
  "vin-til-ribeye": [
    { slug: "ribeye", label: "Ribeye (vin til glasset)" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
  ],
  "vin-til-roastbeef": [
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
  ],
  "vin-til-boef-stroganoff": [
    { slug: "boef-stroganoff-med-hvidvin", label: "Bøf stroganoff med hvidvin" },
    { slug: "svampesovs-med-hvidvin", label: "Svampesovs med hvidvin" },
    { slug: "boef-stroganoff-med-rodvin", label: "Boeuf Stroganoff med rødvin" },
  ],
  "vin-til-bearnaise": [
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
  ],
  "vin-til-stjerneskud": [
    { slug: "rejer-i-hvidvin", label: "Gambas al ajillo" },
    { slug: "fiskefilet-citron-hvidvin", label: "Fiskefilet med citron og hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
  ],
  "vin-til-grill-og-bbq": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
    { slug: "chimichurri-med-rodvin", label: "Chimichurri med rødvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvins-rosmarinmarinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "provencal-hvidvins-hvidloegsmarinade", label: "Provence-kylling" },
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
    { slug: "rodvins-chiliglace-bbq", label: "Rødvins-chiliglace BBQ" },
  ],
  "vin-til-kartoffelmad": [
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
    { slug: "kartoffelmos-med-hvidvin", label: "Kartoffelmos med hvidvin" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-italiensk-mad": [
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "kylling-piccata-med-hvidvin", label: "Kylling piccata med hvidvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "pesto-med-hvidvin", label: "Pesto med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "carpaccio-med-hvidvindressing", label: "Carpaccio med hvidvindressing" },
    { slug: "tiramisu-med-marsala-og-hvidvin", label: "Tiramisu med marsala og hvidvin" },
    { slug: "panna-cotta-med-hvidvin", label: "Panna cotta med hvidvin" },
    { slug: "ossobuco-med-rodvin", label: "Ossobuco med rødvin og gremolata" },
    { slug: "saltimbocca-alla-romana", label: "Saltimbocca alla Romana" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone di Verdure" },
    { slug: "taralli-med-hvidvin", label: "Taralli med hvidvin" },
    { slug: "focaccia-med-hvidvin", label: "Focaccia med hvidvin" },
  ],
  "vin-til-spansk-mad": [
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
    { slug: "paella-med-hvidvin", label: "Paella med hvidvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "sangria-med-rodvin", label: "Sangria med rødvin" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "polbo-a-feira-med-albarino", label: "Polbo á Feira med Albariño" },
  ],
  "vin-til-wok": [
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
    { slug: "wok-rejer-hvidvin", label: "Wok-rejer med hvidvin" },
  ],
  "vin-til-oksekoed": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "hakkeboef-i-rodvinssauce", label: "Hakkebøf i rødvinsauce" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "biksemad-med-rodvin", label: "Biksemad med rødvin" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvins-rosmarinmarinade" },
    { slug: "portvins-hvidloegsmarinade", label: "Portvins-hvidløgsmarinade" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
    { slug: "syrlig-rodvin-balsamicomarinade", label: "Syrlig balsamicomarinade" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico- og rødvinssirup til steak" },
    { slug: "sauce-bordelaise", label: "Sauce Bordelaise" },
    { slug: "madeirasauce", label: "Madeirasauce" },
  ],
  "vin-til-lam": [
    { slug: "lammesteg-med-rodvin-rosmarin", label: "Lammesteg med rødvin og rosmarin" },
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
    { slug: "lammegryde-mynte-hvidvin", label: "Lammegryde med mynte og hvidvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
    { slug: "portvin-mynte-lammemarinade", label: "Port-mynte-lam" },
    { slug: "rodvin-hvidloeg-rosmarinmarinade-til-lam", label: "Rosmarin til lam" },
  ],
  "vin-til-svinekoed": [
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "svinefilet-i-rodvinssauce", label: "Svinefilet i rødvinsauce" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "svinebryst-braiseret-i-rodvin", label: "Svinebryst braiseret i rødvin" },
    { slug: "morbradgryde-med-hvidvin", label: "Mørbradgryde med hvidvin" },
    { slug: "svinekaeber-i-portvinsreduktion", label: "Svinekæber i portvinsreduktion" },
    { slug: "glaseret-skinke-med-madeirasauce", label: "Glaseret skinke med Madeirasauce" },
    { slug: "morbradgryde-med-paprika-og-hvidvin", label: "Mørbradgryde med paprika" },
    { slug: "svinekoteletter-med-sennep-og-hvidvin", label: "Svinekoteletter med sennep og hvidvin" },
    { slug: "hvidvins-sennepsmarinade", label: "Hvidvins-sennepsmarinade" },
    { slug: "sherry-appelsinmarinade", label: "Sherry-appelsinmarinade" },
    { slug: "italiensk-hvidvins-salviemarinade", label: "Salviemarinade" },
    { slug: "rodvins-paprikamarinade", label: "Rødvins-paprikamarinade" },
    { slug: "hvidvins-citron-oreganomarinade", label: "Citron-oreganomarinade" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
    { slug: "marsalasauce-til-svinekoed", label: "Marsalasauce til svinekød" },
    { slug: "rodvins-balsamicosauce", label: "Rødvins-balsamicosauce" },
    { slug: "hvidvins-dijonsauce", label: "Hvidvins-dijonsauce" },
    { slug: "aeble-hvidvins-skysauce", label: "Æble-hvidvins-skysauce" },
    { slug: "cidresauce-med-skalotteloeg", label: "Cidresauce" },
  ],
  "sangiovese-til-pasta": [
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
  ],
  "vin-til-kylling-og-lyst-koed": [
    { slug: "kylling-piccata-med-hvidvin", label: "Kylling piccata med hvidvin" },
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "kyllingefilet-i-rodvin-med-svampe", label: "Kyllingefilet i rødvin" },
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "citronkylling-i-hvidvin", label: "Citronkylling i hvidvin" },
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
    { slug: "poulet-a-lestragon", label: "Poulet à l'Estragon" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin" },
    { slug: "kylling-i-hvidvinssauce-med-porrer-og-vindruer", label: "Kylling med porrer og vindruer" },
    { slug: "kylling-teriyaki-med-sake-og-mirin", label: "Kylling Teriyaki" },
    { slug: "provencal-hvidvins-hvidloegsmarinade", label: "Provencalsk marinade" },
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
    { slug: "marsala-svampemarinade", label: "Marsala-svampe" },
    { slug: "hvidvins-estragonmarinade", label: "Estragonmarinade" },
    { slug: "hvidvins-karrymarinade", label: "Karrymarinade" },
    { slug: "hvidvins-estragonglace-til-kylling", label: "Hvidvins-estragonglace til kylling" },
  ],
  "vin-til-vegetar-og-gront": [
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
    { slug: "ratatouille-med-hvidvin", label: "Ratatouille med hvidvin" },
    { slug: "vegetar-gryderet-rodvin", label: "Vegetar-gryderet med rødvin" },
    { slug: "shakshuka-med-hvidvin", label: "Shakshuka med hvidvin" },
    { slug: "hummus-med-hvidvin", label: "Hummus med hvidvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "marinerede-oliven-med-hvidvin", label: "Marinerede oliven med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "bagt-graeskar-med-salviesmoer", label: "Bagt græskar med salviesmør" },
    { slug: "svampetoast-med-hvidvin-og-timian", label: "Svampetoast med hvidvin" },
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Jordskokkesuppe" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
    { slug: "braiseret-spidskaal-i-hvidvin", label: "Braiseret spidskål i hvidvin" },
    { slug: "svampe-rodvinspostej", label: "Svampe-rødvinspostej" },
    { slug: "belugalinser-i-rodvin", label: "Belugalinser i rødvin" },
  ],
  "vin-til-nachos": [
    { slug: "nachos-med-rodvinskaesesovs", label: "Nachos med rødvinskaesesovs" },
  ],
  "vin-til-kebab-og-shawarma": [
    { slug: "shawarma-tallerken", label: "Shawarma-tallerken (vin til glasset)" },
    { slug: "shawarma-kylling-med-hvidvin", label: "Shawarma-kylling med hvidvin" },
    { slug: "kebab-spyd-med-rodvin", label: "Kebab-spyd med rødvin" },
  ],
  "vin-til-burger": [
    { slug: "burger-med-rodvinsglace", label: "Gourmet-burger med rødvinssautérede løg" },
    { slug: "rodvins-loegkompot", label: "Rødvins-løgkompot" },
    { slug: "portvins-baconmarmelade", label: "Portvins-baconmarmelade" },
    { slug: "hvidvins-jalapenorelish", label: "Hvidvins-jalapeñorelish" },
    { slug: "oel-rodvinssennep", label: "Øl- og rødvinssennep" },
    { slug: "rodvinssyltede-roedloeg", label: "Rødvinssyltede rødløg" },
  ],
  "vin-til-pho": [
    { slug: "pho-kylling-med-hvidvin", label: "Pho med kylling og hvidvin" },
  ],
  "vin-til-ramen": [
    { slug: "ramen-kylling-med-hvidvin", label: "Ramen med kylling og hvidvin" },
  ],
  "vin-til-tacos": [
    { slug: "tacos-med-oksekoed", label: "Tacos med oksekød (vin til glasset)" },
    { slug: "tacos-med-rodvin-okse", label: "Tacos med okse og rødvin" },
  ],
  "vin-til-karryretter": [
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "hvidvins-karrymarinade", label: "Hvidvins-karry" },
  ],
  "vin-til-ceviche": [
    { slug: "ceviche-med-hvidvin", label: "Ceviche med hvidvin" },
  ],
  "vin-til-quiche": [
    { slug: "quiche-med-hvidvin", label: "Quiche med hvidvin" },
  ],
  "vin-til-sild": [
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "stegte-sild-i-hvidvin", label: "Stegte sild i hvidvin" },
  ],
  "vin-til-falafel-og-hummus": [
    { slug: "falafel-tallerken", label: "Falafel-tallerken (vin til glasset)" },
    { slug: "falafel-tallerken-med-hvidvin", label: "Falafel-tallerken med hvidvin" },
  ],
  "vin-til-asiatisk-mad": [
    { slug: "pad-thai-med-hvidvin", label: "Pad thai med hvidvin" },
    { slug: "dim-sum-kylling-hvidvin", label: "Dim sum med kylling og hvidvin" },
    { slug: "couscous-kylling-med-hvidvin", label: "Couscous med kylling og hvidvin" },
    { slug: "pho-kylling-med-hvidvin", label: "Pho med kylling og hvidvin" },
    { slug: "ramen-kylling-med-hvidvin", label: "Ramen med kylling og hvidvin" },
    { slug: "sticky-pork-belly-med-shaoxing", label: "Sticky pork belly med Shaoxing" },
    { slug: "rosenkaal-med-hvidvin-og-oestersauce", label: "Rosenkål med hvidvin og østerssauce" },
    { slug: "asiatisk-rodvin-ingefaermarinade", label: "Asiatisk rødvin-ingefærmarinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "hvidvins-karrymarinade", label: "Karrymarinade" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Shaoxing" },
    { slug: "sake-ingefaersirup", label: "Sake- og ingefærsirup" },
    { slug: "aegte-teriyakisauce", label: "Ægte teriyakisauce" },
    { slug: "shaoxing-hoisin-glace", label: "Shaoxing-hoisin-glace" },
    { slug: "miso-sakesauce", label: "Miso- og sakesauce" },
  ],
  "vin-til-laks": [
    { slug: "grillet-laks-hvidvin-dressing", label: "Grillet laks med hvidvindressing" },
    { slug: "dampet-laks-med-rosevinssauce", label: "Dampet laks med rosévinssauce" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
    { slug: "hvidvins-dildmarinade", label: "Dildmarinade" },
    { slug: "miso-sakesauce", label: "Miso- og sakesauce" },
  ],
  "vin-til-sushi": [
    { slug: "dim-sum-kylling-hvidvin", label: "Dim sum med kylling og hvidvin" },
  ],
  "vin-til-stegt-flaesk": [
    { slug: "stegt-flaesk-med-persillesovs", label: "Stegt flæsk med persillesovs (vin til glasset)" },
    { slug: "stegt-flaesk-i-hvidvinsauce", label: "Stegt flæsk i hvidvinsauce" },
    { slug: "persillesovs-med-hvidvin", label: "Persillesovs med hvidvin" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
  ],
  "vin-til-smorrebrod": [
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "stegte-sild-i-hvidvin", label: "Stegte sild i hvidvin" },
    { slug: "aebleflaesk-med-hvidvin", label: "Æbleflæsk med hvidvin" },
    { slug: "frikadeller-i-hvidvinsauce", label: "Frikadeller i hvidvinsauce" },
    { slug: "rejesalat-med-hvidvin", label: "Rejesalat med hvidvin" },
    { slug: "oel-rodvinssennep", label: "Øl- og rødvinssennep" },
    { slug: "hvidvins-jalapenorelish", label: "Hvidvins-jalapeñorelish" },
    { slug: "hvidvinssyltede-agurker-med-dild", label: "Hvidvinssyltede agurker med dild" },
    { slug: "sherrysyltede-sennepsfro", label: "Sherrysyltede sennepsfrø" },
    { slug: "hvidvinssyltede-gronne-tomater", label: "Hvidvinssyltede grønne tomater" },
    { slug: "roedvins-rugbrod", label: "Rødvins-rugbrød" },
  ],
  "vin-til-rejer": [
    { slug: "rejesalat-med-hvidvin", label: "Rejesalat med hvidvin" },
    { slug: "rejer-i-hvidvin", label: "Gambas al ajillo" },
    { slug: "wok-rejer-hvidvin", label: "Wok-rejer med hvidvin" },
    { slug: "kaemperejer-dampet-i-hvidvin", label: "Dampede kæmperejer i hvidvin" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "ingefaer-chili-hvidvinsmarinade", label: "Ingefær-chili" },
  ],
  "vin-til-koldskaal": [
    { slug: "koldskal-med-hvidvin", label: "Koldskål med hvidvin" },
  ],
  "vin-til-flaesketesteg": [
    { slug: "flaesketesteg-med-rodvin-i-brun-sovs", label: "Flæskesteg med rødvin i brun sovs" },
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "aeble-hvidvinskompot-med-timian", label: "Æble- og hvidvinskompot med timian" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
    { slug: "sherry-honning-glace-til-skinke", label: "Sherry-honning-glace til skinke" },
    { slug: "madeirasauce", label: "Madeirasauce" },
    { slug: "aeble-hvidvins-skysauce", label: "Æble-hvidvins-skysauce" },
    { slug: "cidresauce-med-skalotteloeg", label: "Cidresauce" },
  ],
  "vin-til-graesk-mad": [
    { slug: "moussaka-med-rodvin", label: "Moussaka med rødvin" },
    { slug: "paella-med-hvidvin", label: "Paella med hvidvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino (tapas-stil)" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
    { slug: "kleftiko-med-hvidvin", label: "Kleftiko med hvidvin" },
    { slug: "stifado-med-rodvin", label: "Stifado med rødvin" },
    { slug: "hvidvins-citrondampede-artiskokker", label: "Hvidvins-artiskokker" },
    { slug: "gigantes-plaki-med-hvidvin", label: "Gigantes plaki med hvidvin" },
    { slug: "kokkinisto-med-rodvin", label: "Kokkinisto med rødvin" },
  ],
  "vin-til-mortensaften": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-poelser-og-kartoffel": [
    { slug: "poelser-i-rodvinsglace", label: "Pølser i rødvinsglace" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
  ],
  "vin-til-salat": [
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
  ],
  "vin-til-roedgroed": [
    { slug: "roedgroed-med-portvin", label: "Rødgrød med portvin" },
  ],
  "vin-til-kalkun": [
    { slug: "kalkunsteg-med-hvidvin", label: "Kalkunsteg med hvidvin" },
    { slug: "hvidvins-estragonmarinade", label: "Estragon til fjerkræ" },
  ],
  "vin-til-hummer": [
    { slug: "hummer-i-hvidvinsauce", label: "Hummer i hvidvinsauce" },
    { slug: "grillede-jomfruhummere-med-hvidloegssmoer", label: "Grillede jomfruhummere" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque med cognac og hvidvin" },
  ],
  "vin-til-paaske-og-paaskefrokost": [
    { slug: "lammesteg-med-rodvin-rosmarin", label: "Lammesteg med rødvin og rosmarin" },
  ],
  "vin-til-mexicansk-mad": [
    { slug: "enchiladas-med-rodvin", label: "Enchiladas med rødvin" },
    { slug: "chili-lime-hvidvinsmarinade", label: "Chili-lime-marinade" },
    { slug: "carnitas-med-hvidvin", label: "Carnitas med hvidvin" },
    { slug: "chili-verde-med-hvidvin", label: "Chili Verde med hvidvin" },
    { slug: "birria-med-rodvin", label: "Birria med rødvin" },
  ],
  "vin-til-thai-mad": [
    { slug: "thai-gron-karry-med-hvidvin", label: "Thai grøn karry med hvidvin" },
    { slug: "tom-kha-gai-med-hvidvin", label: "Tom Kha Gai med hvidvin" },
  ],
  "vin-til-brittisk-mad": [
    { slug: "shepherd-pie-med-rodvin", label: "Shepherd's pie med rødvin" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "fish-and-chips-med-hvidvin", label: "Fish and chips med hvidvin" },
    { slug: "guinness-olbrod", label: "Guinness-ølbrød" },
  ],
  "vin-til-vietnamesisk-mad": [
    { slug: "bun-cha-med-hvidvin", label: "Bun cha med hvidvin" },
  ],
  "vin-til-kinesisk-mad": [
    { slug: "kung-pao-kylling-med-hvidvin", label: "Kung pao kylling med hvidvin" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Femkrydderi" },
    { slug: "drunken-chicken-med-shaoxing", label: "Drunken chicken med Shaoxing" },
    { slug: "mapo-tofu-med-shaoxing", label: "Mapo tofu med Shaoxing" },
    { slug: "char-siu-med-shaoxing", label: "Char siu med Shaoxing" },
  ],
  "vin-til-spareribs": [
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
    { slug: "rodvins-chiliglace-bbq", label: "Rødvins-chiliglace BBQ" },
  ],
  "vin-til-aebleskiver": [
    { slug: "aebleskiver-med-hvidvin", label: "Æbleskiver med hvidvin" },
  ],
  "vin-til-frikadeller": [
    { slug: "frikadeller-med-kartofler", label: "Frikadeller med kartofler (vin til glasset)" },
    { slug: "frikadeller-i-hvidvinsauce", label: "Frikadeller i hvidvinsauce" },
    { slug: "karbonader-i-hvidvinsauce", label: "Karbonader i hvidvinsauce" },
  ],
  "vin-til-torsk": [
    { slug: "torsk-i-rodvinsauce", label: "Torsk i rødvinsauce" },
    { slug: "torsk-i-hvidvin", label: "Torsk i hvidvin" },
    { slug: "helleflynder-med-hvidvin", label: "Helleflynder med hvidvin" },
    { slug: "hvidvinsdampet-torsk-med-porrer-og-safran", label: "Hvidvinsdampet torsk med porrer og safran" },
    { slug: "hvidvinsdampet-torsk-en-papillote", label: "Hvidvinsdampet torsk en papillote" },
  ],
  "vin-til-moussaka": [
    { slug: "moussaka-med-rodvin", label: "Moussaka med rødvin" },
  ],
  "vin-til-carbonara": [
    { slug: "carbonara-med-hvidvin", label: "Carbonara med hvidvin" },
  ],
  "vin-til-risotto": [
    { slug: "risotto-med-hvidvin", label: "Risotto med hvidvin" },
    { slug: "skaldyrsrisotto-med-hvidvin", label: "Skaldyrsrisotto med hvidvin" },
  ],
  "vin-til-paella": [
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
  ],
  "vin-til-chili-con-carne": [
    { slug: "chili-con-carne-med-rodvin", label: "Chili con carne med rødvin" },
  ],
  "vin-til-medister": [
    { slug: "medister-med-kartofler", label: "Medister med kartofler (vin til glasset)" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
  ],
  "vin-til-gulasch": [
    { slug: "gullasch-med-rodvin", label: "Gullasch med rødvin" },
    { slug: "gullaschsuppe-med-rodvin", label: "Gullaschsuppe med rødvin" },
    { slug: "bigos-med-rodvin", label: "Bigos med rødvin" },
  ],
  "vin-til-muslinger": [
    { slug: "muslinger-i-hvidvin", label: "Muslinger i hvidvin" },
    { slug: "muslinger-i-hvidvin-og-safran", label: "Muslinger i hvidvin og safran" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "skaldyrsrisotto-med-hvidvin", label: "Skaldyrsrisotto" },
  ],
  "vin-til-blaeksprutte": [
    { slug: "blaeksprutte-i-rodvin", label: "Blæksprutte i rødvin" },
    { slug: "polbo-a-feira-med-albarino", label: "Polbo á Feira" },
  ],
  "vin-til-fondue": [
    { slug: "fondue-med-hvidvin", label: "Fondue med hvidvin" },
  ],
  "vin-til-shakshuka": [
    { slug: "shakshuka-med-hvidvin", label: "Shakshuka med hvidvin" },
  ],
  "vin-til-and": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "andebaer-portvin-sauce", label: "Andebryst med portvinsauce" },
    { slug: "andeconfit-med-rodvin", label: "Andeconfit med rødvin" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
    { slug: "rodvinsmarineret-andebryst", label: "Rødvinsmarineret andebryst" },
    { slug: "andebryst-med-brombaer-rodvinssauce", label: "Andebryst med brombær-rødvinssauce" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Shaoxing-and" },
    { slug: "aeble-hvidvinskompot-med-timian", label: "Æble- og hvidvinskompot med timian" },
    { slug: "portvinsglasering-til-and-og-flaeskesteg", label: "Portvinsglasering til and" },
    { slug: "shaoxing-hoisin-glace", label: "Shaoxing-hoisin-glace" },
    { slug: "gloegg-sauce-til-julestegen", label: "Gløgg-sauce til julestegen" },
  ],
  "vin-til-gas": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "andeconfit-med-rodvin", label: "Andeconfit med rødvin" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
  ],
  "vin-til-dessert-og-kransekage": [
    { slug: "paerer-i-rodvin", label: "Pærer i rødvin" },
    { slug: "aebletaerte-med-calvados-og-hvidvin", label: "Æbletærte med calvados og hvidvin" },
    { slug: "aeblekage-hvidvin-karamel", label: "Æblekage med hvidvin-karamel" },
    { slug: "zabaglione-med-hvidvin", label: "Zabaglione med hvidvin" },
    { slug: "tiramisu-med-marsala-og-hvidvin", label: "Tiramisu med marsala og hvidvin" },
    { slug: "creme-brulee-med-hvidvin", label: "Crème brûlée med hvidvin" },
    { slug: "panna-cotta-med-hvidvin", label: "Panna cotta med hvidvin" },
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
    { slug: "champagne-jordbaersorbet", label: "Champagne-jordbærsorbet" },
    { slug: "chokolade-trofler-med-portvin", label: "Chokoladetrøfler med portvin" },
    { slug: "hvidvinsbagede-fersken", label: "Hvidvinsbagede ferskner" },
    { slug: "rose-granite-med-hindbaer", label: "Rosé-granité med hindbær" },
    { slug: "mousserende-vingele-med-friske-baer", label: "Mousserende vingelé med bær" },
    { slug: "moscato-dasti-sorbet", label: "Moscato d'Asti sorbet" },
    { slug: "sherry-trifle", label: "Sherry Trifle" },
    { slug: "paerer-i-hvidvin-og-safran", label: "Pærer i hvidvin og safran" },
    { slug: "plommetrifli-med-rodvinssirup", label: "Plommetrifli med rødvinssirup" },
    { slug: "hvidvinsgele-med-sommerbaer", label: "Hvidvinsgelé med sommerbær" },
    { slug: "rodvinssorbet-med-brombaer", label: "Rødvinssorbet med brombær" },
    { slug: "tarte-tatin-med-hvidvinskaramel", label: "Tarte Tatin med hvidvinskaramel" },
    { slug: "moscato-pocherede-ferskner", label: "Moscato-pocherede ferskner" },
    { slug: "rodvinssirup-med-vanilje", label: "Rødvinssirup med vanilje" },
    { slug: "champagne-jordbaersirup", label: "Champagne- og jordbærsirup" },
    { slug: "rabarberkompot-med-rose", label: "Rabarberkompot med rosé" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
    { slug: "espresso-marsalasirup", label: "Espresso- og Marsalasirup" },
    { slug: "rose-hindbaercoulis", label: "Rosé-hindbærcoulis" },
    { slug: "pocherede-rabarber-i-moscato", label: "Pocherede rabarber i Moscato" },
    { slug: "appelsinsalat-campari-vermouthsirup", label: "Appelsinsalat med Campari-sirup" },
    { slug: "cantucci-med-vinsanto", label: "Cantucci med Vin Santo" },
    { slug: "madeira-kage-med-madeira", label: "Madeira-kage med Madeira" },
    { slug: "champagne-brioche", label: "Champagne-brioche" },
    { slug: "clafoutis-med-hvidvin", label: "Clafoutis med hvidvin" },
  ],
  "vin-til-brasiliansk-mad": [
    { slug: "feijoada-med-rodvin", label: "Feijoada med rødvin" },
    { slug: "moqueca-med-hvidvin", label: "Moqueca med hvidvin" },
  ],
  "vin-til-oesters": [
    { slug: "oesters-gratineret-med-hvidvin", label: "Østers gratineret med hvidvin" },
    { slug: "oesters-med-champagne-sabayonne", label: "Østers med Champagne-sabayonne" },
  ],
  "vin-til-klassisk-fransk-mad": [
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "asparges-i-hvidvinsauce", label: "Asparges i hvidvinsauce" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
    { slug: "blanquette-de-veau-med-hvidvin", label: "Blanquette de veau med hvidvin" },
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
  ],
  "vin-til-amerikansk-comfort-mad": [
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
  ],
  "vin-til-tatar-og-carpaccio": [
    { slug: "carpaccio-med-hvidvindressing", label: "Carpaccio med hvidvindressing" },
    { slug: "boeftatar-med-hvidvin", label: "Bøftatar med hvidvin" },
  ],
  "vin-til-asparges": [
    { slug: "asparges-i-hvidvinsauce", label: "Asparges i hvidvinsauce" },
    { slug: "champagne-hollandaise", label: "Champagne-hollandaise" },
  ],
  "vin-i-cocktails-spritz-og-drikke": [
    { slug: "sangria-med-rodvin", label: "Sangria med rødvin" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "vin-til-indisk-mad": [
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "kylling-biryani-med-hvidvin", label: "Kyllingebiryani med hvidvin" },
    { slug: "rogan-josh-med-rodvin", label: "Rogan josh med rødvin" },
  ],
  "vin-til-fisk-og-chips": [
    { slug: "fish-and-chips", label: "Fish and chips (vin til glasset)" },
    { slug: "fish-and-chips-med-hvidvin", label: "Fish and chips med hvidvin" },
  ],
  "vin-til-marokkansk-mad": [
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
  ],
  "vin-til-oktoberfest-mad": [
    { slug: "wiener-schnitzel-med-hvidvin", label: "Wiener schnitzel med hvidvin" },
  ],
  "vin-til-alsace-mad": [
    { slug: "wiener-schnitzel-med-hvidvin", label: "Wiener schnitzel med hvidvin" },
  ],
  "vin-til-crepes-og-pandekager": [
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
  ],
  "vin-til-sommer": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "piknik-sandwich-med-hvidvin-dressing", label: "Piknik-sandwich med hvidvin-dressing" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-piknik": [
    { slug: "piknik-sandwich-med-hvidvin-dressing", label: "Piknik-sandwich med hvidvin-dressing" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-haveselskab": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "bedste-sommervin": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-grillet-gront": [
    { slug: "ratatouille-med-hvidvin", label: "Ratatouille med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "hvidvinsbraiserede-porrer", label: "Hvidvinsbraiserede porrer" },
    { slug: "rosenkaal-med-hvidvin-og-oestersauce", label: "Rosenkål med hvidvin og østerssauce" },
    { slug: "hvidvins-urtemarinade-groentsager", label: "Urte-grønt" },
  ],

  "vin-til-ost-og-ostebord": [
    { slug: "portvins-fignemarmelade-med-rosmarin", label: "Portvins-fignemarmelade" },
    { slug: "gorgonzola-creme-med-portvin", label: "Gorgonzola-creme med portvin" },
    { slug: "mini-hvidvinsfondue-tapas", label: "Mini-hvidvinsfondue" },
    { slug: "klar-rodvinsgele-med-vanilje", label: "Klar rødvinsgelé" },
    { slug: "tranebaekompot-grand-marnier-rodvin", label: "Tranebærkompot med Grand Marnier" },
    { slug: "chorizomarmelade-med-sherry", label: "Chorizomarmelade med sherry" },
    { slug: "rabarberkompot-med-rose", label: "Rabarberkompot med rosé" },
    { slug: "moscato-abrikoskompot", label: "Moscato-abrikoskompot" },
    { slug: "pocherede-blommer-i-rodvin-og-nelliker", label: "Pocherede blommer i rødvin" },
    { slug: "sherry-karamelliserede-valnodder", label: "Sherry-karamelliserede valnødder" },
    { slug: "hvidvinssyltede-havtorn", label: "Hvidvinssyltede havtorn" },
  ],

  "vin-til-gedeost": [
    { slug: "rodvinsglaserede-figner-med-gedeost", label: "Rødvinsglaserede figner med gedeost" },
    { slug: "gedeost-crostini-med-skalotteloeg", label: "Gedeost-crostini med skalotteløg" },
  ],

  "vin-til-brie-og-camembert": [
    { slug: "bagt-camembert-med-hvidvin", label: "Bagt camembert med hvidvin" },
  ],

  "vin-til-foie-gras": [
    { slug: "sauternes-gele-med-safran", label: "Sauternes-gelé med safran" },
  ],

  "champagne-til-mad": [
    { slug: "champagne-jordbaersorbet", label: "Champagne-jordbærsorbet" },
    { slug: "hummersuppe-med-cognac-og-bobler", label: "Hummersuppe med cognac og bobler" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med mousserende sabayon" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Mousserende fisk" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "bedste-rosevin": [
    { slug: "dampet-laks-med-rosevinssauce", label: "Dampet laks med rosévinssauce" },
    { slug: "cremet-pastasalat-med-melon-og-parma", label: "Pastasalat med melon og parma" },
  ],
  "portvin-til-ost": [
    { slug: "portvinsglaserede-figner-med-gedeost", label: "Portvinsglaserede figner med gedeost" },
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
    { slug: "figner-i-krydret-portvinssirup", label: "Figner i portvinssirup" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
  ],
  "riesling-til-asiatisk-mad": [
    { slug: "tom-kha-gai-med-hvidvin", label: "Tom Kha Gai med hvidvin" },
    { slug: "gyoza-svinekoed-med-riesling", label: "Gyoza med svinekød" },
    { slug: "sticky-pork-belly-med-shaoxing", label: "Sticky pork belly" },
  ],
  "vin-til-dim-sum": [
    { slug: "gyoza-svinekoed-med-riesling", label: "Gyoza med svinekød" },
  ],
  "vin-til-svampe": [
    { slug: "svampetoast-med-hvidvin-og-timian", label: "Svampetoast med hvidvin" },
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "marsala-svampemarinade", label: "Marsala-porcini" },
    { slug: "cremet-svampesuppe-med-madeira", label: "Cremet svampesuppe med Madeira" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
    { slug: "portvinssyltede-svampe", label: "Portvinssyltede svampe" },
    { slug: "svampe-rodvinspostej", label: "Svampe-rødvinspostej" },
  ],
  "vin-til-bourgogne-mad": [
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
  ],
  "sadan-bruger-du-vin-til-sauce-og-simren": [
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "balsamico-rodvinsglaserede-skalotteloeg", label: "Glaserede skalotteløg" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "hvidvinsbraiserede-porrer", label: "Hvidvinsbraiserede porrer" },
    { slug: "kylling-i-hvidvinssauce-med-porrer-og-vindruer", label: "Kylling med vindruer" },
    { slug: "svinekoteletter-med-sennep-og-hvidvin", label: "Sennep-hvidvinssauce" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Hvidvinsreduktion til suppe" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvinsmarinade" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "beurre-blanc", label: "Beurre blanc" },
    { slug: "rodvins-loegkompot", label: "Rødvins-løgkompot" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico-rødvinssirup" },
    { slug: "hvidvins-estragonglace-til-kylling", label: "Hvidvins-estragonglace" },
    { slug: "rodvinssirup-med-vanilje", label: "Rødvinssirup med vanilje" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
    { slug: "espresso-marsalasirup", label: "Espresso-Marsalasirup" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
    { slug: "portvinsglasering-til-and-og-flaeskesteg", label: "Portvinsglasering" },
    { slug: "sherry-honning-glace-til-skinke", label: "Sherry-honning-glace" },
    { slug: "hvidvins-troffelmayo", label: "Hvidvins-trøffelmayo" },
    { slug: "rodvins-chiliglace-bbq", label: "Rødvins-chiliglace BBQ" },
    { slug: "hvidvins-hvidloegsconfit", label: "Hvidløgsconfit med hvidvin" },
    { slug: "kleftiko-med-hvidvin", label: "Kleftiko" },
    { slug: "stifado-med-rodvin", label: "Stifado" },
    { slug: "focaccia-med-hvidvin", label: "Focaccia med hvidvin" },
    { slug: "braiseret-spidskaal-i-hvidvin", label: "Braiseret spidskål" },
    { slug: "belugalinser-i-rodvin", label: "Belugalinser i rødvin" },
    { slug: "chili-verde-med-hvidvin", label: "Chili Verde" },
    { slug: "kokkinisto-med-rodvin", label: "Kokkinisto" },
    { slug: "birria-med-rodvin", label: "Birria" },
    { slug: "rogan-josh-med-rodvin", label: "Rogan josh" },
    { slug: "sauce-bordelaise", label: "Sauce Bordelaise" },
    { slug: "portvins-morkelsauce", label: "Portvins-morkelsauce" },
    { slug: "portvinsglace", label: "Portvinsglace" },
    { slug: "marsalasauce-til-svinekoed", label: "Marsalasauce" },
    { slug: "rodvins-balsamicosauce", label: "Rødvins-balsamicosauce" },
    { slug: "madeirasauce", label: "Madeirasauce" },
    { slug: "hvidvins-dijonsauce", label: "Hvidvins-dijonsauce" },
    { slug: "beurre-rouge", label: "Beurre rouge" },
    { slug: "champagne-hollandaise", label: "Champagne-hollandaise" },
    { slug: "aegte-teriyakisauce", label: "Ægte teriyakisauce" },
    { slug: "shaoxing-hoisin-glace", label: "Shaoxing-hoisin-glace" },
    { slug: "miso-sakesauce", label: "Miso-sakesauce" },
    { slug: "aeble-hvidvins-skysauce", label: "Æble-hvidvins-skysauce" },
    { slug: "cidresauce-med-skalotteloeg", label: "Cidresauce" },
    { slug: "sherry-groen-pebersauce", label: "Sherry-grøn pebersauce" },
  ],
  "vin-til-svinekam": [
    { slug: "glaseret-skinke-med-madeirasauce", label: "Glaseret skinke med Madeirasauce" },
    { slug: "hvidvinsmarineret-svinekam", label: "Hvidvinsmarineret svinekam" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
  ],
  "bedste-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
    { slug: "portvins-hvidloegsmarinade", label: "Portvins-hvidløgsmarinade" },
    { slug: "portvin-mynte-lammemarinade", label: "Portvin til lam" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
    { slug: "portvin-tonic", label: "Portvin-tonic (P&T)" },
    { slug: "figner-i-krydret-portvinssirup", label: "Figner i portvinssirup" },
  ],
  "hvad-er-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "portvin-mynte-lammemarinade", label: "Port i marinade" },
    { slug: "portvin-tonic", label: "Portvin-tonic" },
  ],
  "sadan-serverer-du-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "portvin-tonic", label: "Portvin-tonic" },
  ],
  "hvid-portvin": [
    { slug: "portvin-tonic", label: "Portvin-tonic (Port & Tonic)" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],
  "portvin-til-risalamande": [
    { slug: "risalamande", label: "Risalamande" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],
  "hvad-er-colheita": [
    { slug: "portvinsglaserede-figner-med-gedeost", label: "Portvinsglaserede figner med gedeost" },
  ],
  "lbv-ufiltreret-vs-filtreret": [
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
    { slug: "chokolademousse-med-portvin", label: "Chokolademousse med portvin" },
  ],
  "vintage-portvin-dekantering": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
  ],
  "douro-dalen-subregioner": [
    { slug: "portvin-tonic", label: "Portvin-tonic" },
    { slug: "bifana", label: "Bifana" },
  ],
  "vin-til-juleaften": [
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
    { slug: "brune-kartofler-med-portvin", label: "Brune kartofler med portvin" },
    { slug: "syltede-roedbeder-med-rodvin", label: "Syltede rødbeder med rødvin" },
  ],
  "vin-til-julemad-den-store-guide": [
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
    { slug: "gloegg-sauce-til-julestegen", label: "Gløgg-sauce til julestegen" },
  ],
  "vin-til-juleand": [
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
    { slug: "gloegg-sauce-til-julestegen", label: "Gløgg-sauce til julestegen" },
  ],
  "pinot-noir-til-and": [
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
  ],
  "portvin-til-chokolade": [
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
  ],
  "vin-til-chokolademousse": [
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
  ],
  "bedste-dessertvin": [
    { slug: "moscato-dasti-sorbet", label: "Moscato d'Asti sorbet" },
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
    { slug: "paerer-i-hvidvin-og-safran", label: "Pærer i hvidvin og safran" },
    { slug: "plommetrifli-med-rodvinssirup", label: "Plommetrifli med rødvinssirup" },
    { slug: "hvidvinsgele-med-sommerbaer", label: "Hvidvinsgelé med sommerbær" },
    { slug: "rodvinssorbet-med-brombaer", label: "Rødvinssorbet med brombær" },
    { slug: "tarte-tatin-med-hvidvinskaramel", label: "Tarte Tatin med hvidvinskaramel" },
    { slug: "moscato-pocherede-ferskner", label: "Moscato-pocherede ferskner" },
  ],
  "hvad-er-sherry-vin": [
    { slug: "sherry-trifle", label: "Sherry Trifle" },
    { slug: "sherry-appelsinmarinade", label: "Sherry-appelsinmarinade" },
  ],
  "chardonnay-til-fisk": [
    { slug: "hvidvinsdampet-torsk-en-papillote", label: "Torsk en papillote" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
  ],
  "vin-til-oksekoed-i-sauce": [
    { slug: "boef-stroganoff-med-rodvin", label: "Boeuf Stroganoff med rødvin" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce" },
  ],
  "vin-til-vildt": [
    { slug: "vildtgryde-med-portvin-og-enebaer", label: "Vildtgryde med portvin og enebær" },
    { slug: "rodvin-enebaermarinade", label: "Enebærmarinade" },
    { slug: "rodvinssyltede-tyttebaer", label: "Rødvinssyltede tyttebær" },
    { slug: "braiseret-raadyrskank-med-rodvin", label: "Braiseret rådyrskank" },
    { slug: "vildsvinegryde-med-rodvin", label: "Vildsvinegryde med rødvin" },
    { slug: "rodvins-chokoladesauce", label: "Rødvins-chokoladesauce" },
    { slug: "sauce-grand-veneur", label: "Sauce Grand Veneur" },
  ],
  "vin-til-blaaskimmelost": [
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
  ],
  "vin-til-baskisk-mad": [
    { slug: "pintxos-txakoli-chorizo", label: "Pintxos med txakoli-chorizo" },
  ],
  "vin-til-japansk-mad": [
    { slug: "kylling-teriyaki-med-sake-og-mirin", label: "Kylling Teriyaki med sake og mirin" },
    { slug: "gyoza-dampet-i-sake", label: "Gyoza dampet i sake" },
    { slug: "klassisk-teriyaki-marinade", label: "Teriyaki" },
    { slug: "sake-misomarinade", label: "Sake-miso" },
    { slug: "sake-dampede-muslinger", label: "Sake-dampede muslinger" },
  ],
  "bedste-bobler": [
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med sabayon" },
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
  ],
  "bobler-til-fredag": [
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
  ],
  "bobler-champagne-cava-prosecco-og-cremant": [
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med sabayon" },
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Champagne-marinade" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "rosevin-til-grill": [
    { slug: "rose-jordbaermarinade", label: "Jordbærmarinade" },
  ],
  "rosevin-til-mad-og-sommer": [
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
  ],
  "hvad-er-madeira-vin": [
    { slug: "madeira-allehaandemarinade", label: "Madeira-marinade" },
    { slug: "cremet-svampesuppe-med-madeira", label: "Svampesuppe med Madeira" },
  ],
  "vin-til-lys-fisk": [
    { slug: "hvidvins-dildmarinade", label: "Hvidvin-dild" },
    { slug: "lime-hvidvins-cevichemarinade", label: "Ceviche-marinade" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Bobler til fisk" },
    { slug: "beurre-blanc", label: "Beurre blanc" },
  ],
  "vin-til-grillet-fisk": [
    { slug: "hvidvins-dildmarinade", label: "Grillet laks" },
    { slug: "ingefaer-chili-hvidvinsmarinade", label: "Grillede rejer" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Fast fisk" },
  ],
  "vin-til-vegetariske-og-veganske-retter": [
    { slug: "hvidvins-urtemarinade-groentsager", label: "Grøntsagsmarinade" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone med hvidvin" },
  ],
  "bedste-julevin": [
    { slug: "roedvinsgloegg", label: "Rødvinsgløgg" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],
  "vin-til-portugisisk-mad": [
    { slug: "churrasco-med-hvidvin-og-hvidloeg", label: "Churrasco med hvidvin" },
    { slug: "carne-de-porco-a-alentejana", label: "Carne de Porco à Alentejana" },
    { slug: "bacalhau-a-bras-med-hvidvin", label: "Bacalhau à Brás med hvidvin" },
    { slug: "arroz-de-pato-med-rodvin", label: "Arroz de Pato med rødvin" },
    { slug: "francesinha-sauce-med-ol-og-vin", label: "Francesinha-sauce" },
  ],
  "vin-til-mellemoestlig-mad": [
    { slug: "imam-bayildi-med-hvidvin", label: "Imam bayildi med hvidvin" },
    { slug: "maqluba-med-hvidvin", label: "Maqluba med hvidvin" },
    { slug: "tyrkisk-guevec-med-rodvin", label: "Tyrkisk güveç med rødvin" },
  ],
  "vin-til-libanesisk-mad": [
    { slug: "maqluba-med-hvidvin", label: "Maqluba med hvidvin" },
  ],
  "vin-til-koreansk-mad": [
    { slug: "bulgogi-med-sake-og-mirin", label: "Bulgogi med sake og mirin" },
    { slug: "galbi-jjim-med-sake", label: "Galbi jjim med sake" },
    { slug: "gochujang-kylling-med-mirin", label: "Gochujang-kylling med mirin" },
  ],
  "vin-til-peruviansk-mad": [
    { slug: "lomo-saltado-med-rodvin", label: "Lomo saltado med rødvin" },
  ],
  "vin-til-argentinsk-mad": [
    { slug: "empanadas-med-rodvin", label: "Empanadas med rødvin" },
    { slug: "bife-de-chorizo-med-malbec", label: "Bife de chorizo med Malbec" },
  ],
  "vin-til-fisk": [
    { slug: "sauce-noilly-prat", label: "Sauce Noilly Prat" },
    { slug: "sauce-bercy", label: "Sauce Bercy" },
    { slug: "hvidvins-veloute-med-urter", label: "Hvidvins-velouté med urter" },
  ],
  "vin-til-kylling": [
    { slug: "sauce-albufera", label: "Sauce Albuféra" },
    { slug: "sherrysauce-med-svampe", label: "Sherrysauce med svampe" },
  ],
  "chill-your-reds": [
    { slug: "stegt-lakseside-med-kold-pinot", label: "Stegt lakseside med kold pinot" },
    { slug: "roert-tatar-med-beaujolais", label: "Rørt tatar med Beaujolais" },
    { slug: "sliders-med-fritter-og-barbera", label: "Sliders med Barbera" },
    { slug: "svamperisotto-med-kold-pinot", label: "Svamperisotto med kold pinot" },
    { slug: "grillet-kyllingebryst-estragon-kold-rodvin", label: "Kylling med estragon" },
    { slug: "sliders-med-barbera-glaze", label: "Sliders med Barbera-glaze" },
    { slug: "grillet-unghanebryst-brombaer-rodvinssauce", label: "Unghanebryst med brombær" },
    { slug: "sprode-gyoza-med-kold-rodvin", label: "Sprøde gyoza med kold rødvin" },
  ],
  "rodvin-til-fisk-kold": [
    { slug: "stegt-lakseside-med-kold-pinot", label: "Stegt lakseside med kold pinot" },
    { slug: "grillet-roedspaette-med-chorizocrumble", label: "Rødspætte med chorizocrumble" },
    { slug: "stegt-torskeryg-med-beurre-rouge", label: "Torskeryg med beurre rouge" },
    { slug: "lynstegt-tunsteak-med-sesam", label: "Lynstegt tunsteak med sesam" },
  ],
  "afkoelt-roedvin": [
    { slug: "stegt-lakseside-med-kold-pinot", label: "Stegt lakseside med kold pinot" },
    { slug: "roert-tatar-med-beaujolais", label: "Rørt tatar med Beaujolais" },
    { slug: "vitello-tonnato-med-dolcetto", label: "Vitello tonnato med Dolcetto" },
    { slug: "svamperisotto-med-kold-pinot", label: "Svamperisotto med kold pinot" },
  ],
  "chillable-reds": [
    { slug: "roert-tatar-med-beaujolais", label: "Rørt tatar med Beaujolais" },
    { slug: "sliders-med-fritter-og-barbera", label: "Sliders med Barbera" },
  ],
  "top-5-druer-til-koeleskabet": [
    { slug: "roert-tatar-med-beaujolais", label: "Tatar + Gamay" },
    { slug: "lynstegt-tunsteak-med-sesam", label: "Tun + Frappato" },
    { slug: "sliders-med-fritter-og-barbera", label: "Sliders + Barbera" },
    { slug: "svamperisotto-med-kold-pinot", label: "Risotto + Pinot" },
    { slug: "sliders-med-barbera-glaze", label: "Sliders med Barbera-glaze" },
  ],
  "rodvin-til-terrassen": [
    { slug: "sliders-med-fritter-og-barbera", label: "Sliders med Barbera" },
    { slug: "vitello-tonnato-med-dolcetto", label: "Vitello tonnato" },
    { slug: "charcuteribraet-med-kold-rodvin", label: "Charcuteribræt med kold rødvin" },
    { slug: "tarte-flambee-med-gedeost", label: "Tarte flambée med gedeost" },
    { slug: "luksus-hotdogs-med-rodvinsloeg", label: "Luksus-hotdogs med rødvinssløg" },
    { slug: "grillede-portobello-med-parmesan", label: "Grillede portobello med parmesan" },
    { slug: "sprode-gyoza-med-kold-rodvin", label: "Sprøde gyoza med kold rødvin" },
    { slug: "grillet-halloumi-hvidvins-honningglace", label: "Halloumi med honningglace" },
  ],
  "20-minutter-i-koeleskabet-roedvin": [
    { slug: "luksus-hotdogs-med-rodvinsloeg", label: "Luksus-hotdogs" },
    { slug: "charcuteribraet-med-kold-rodvin", label: "Charcuteribræt" },
  ],
  "vinho-verde-vs-alvarinho": [
    { slug: "arroz-de-marisco", label: "Arroz de marisco" },
    { slug: "polvo-a-lagareiro", label: "Polvo à Lagareiro" },
    { slug: "ameijoas-a-bulhao-pato", label: "Amêijoas à Bulhão Pato" },
    { slug: "pica-pau", label: "Pica-pau" },
    { slug: "cataplana-med-hvidvin", label: "Cataplana" },
  ],
  "farvel-sancerre-goddag-assyrtiko": [
    { slug: "dampede-hjertemuslinger-feta-assyrtiko", label: "Hjertemuslinger med feta" },
    { slug: "rejer-saganaki", label: "Rejer saganaki" },
    { slug: "psarosoupa-graesk-fiskesuppe", label: "Psarosoupa" },
  ],
  "graesk-meze-braet": [
    { slug: "rejer-saganaki", label: "Rejer saganaki" },
    { slug: "dampede-hjertemuslinger-feta-assyrtiko", label: "Hjertemuslinger med feta" },
    { slug: "keftedakia-med-rodvin", label: "Keftedakia" },
    { slug: "grillet-halloumi-hvidvins-honningglace", label: "Halloumi med honningglace" },
  ],
  "vinregion-portugal": [
    { slug: "arroz-de-marisco", label: "Arroz de marisco" },
    { slug: "polvo-a-lagareiro", label: "Polvo à Lagareiro" },
    { slug: "ameijoas-a-bulhao-pato", label: "Amêijoas à Bulhão Pato" },
    { slug: "pica-pau", label: "Pica-pau" },
    { slug: "cataplana-med-hvidvin", label: "Cataplana" },
  ],
  "xinomavro-og-touriga-nacional": [
    { slug: "keftedakia-med-rodvin", label: "Keftedakia" },
  ],
  "douro-vs-dao": [
    { slug: "prego-sandwich", label: "Prego-sandwich" },
    { slug: "bifana", label: "Bifana" },
  ],
  "moschofilero-druen": [
    { slug: "spanakopita-med-hvidvin", label: "Spanakopita" },
    { slug: "feta-saganaki", label: "Feta saganaki" },
  ],
  "agiorgitiko-druen": [
    { slug: "pastitsio-med-rodvin", label: "Pastitsio" },
  ],
  "xinomavro-druen": [
    { slug: "pastitsio-med-rodvin", label: "Pastitsio" },
  ],
  "assyrtiko-druen": [
    { slug: "feta-saganaki", label: "Feta saganaki" },
    { slug: "spanakopita-med-hvidvin", label: "Spanakopita" },
  ],
  "vin-til-feta": [
    { slug: "feta-saganaki", label: "Feta saganaki" },
    { slug: "spanakopita-med-hvidvin", label: "Spanakopita" },
  ],
  "zweigelt-druen": [
    { slug: "sticky-pork-belly-med-kold-zweigelt", label: "Sticky pork med kold Zweigelt" },
    { slug: "grillpoelser-med-kold-zweigelt", label: "Grillpølser med kold Zweigelt" },
  ],
  "schiava-druen": [
    { slug: "speck-braet-med-schiava", label: "Speck-bræt med Schiava" },
  ],
  "frappato-druen": [
    { slug: "sticky-pork-belly-med-kold-zweigelt", label: "Sticky pork (alt: Frappato)" },
  ],
  "bobler-paa-en-tirsdag": [
    { slug: "fried-chicken-med-bobler", label: "Fried chicken med bobler" },
    { slug: "hotdogs-med-cava", label: "Hotdogs med Cava" },
    { slug: "pizza-bianca-mousserende-rose", label: "Pizza bianca" },
    { slug: "smash-burger-med-troffelmayo", label: "Smash burger med trøffelmayo" },
    { slug: "luksus-nachos-med-cava", label: "Nachos med Cava" },
    { slug: "gougeres", label: "Gougères" },
  ],
  "friture-og-bobler": [
    { slug: "fried-chicken-med-bobler", label: "Fried chicken" },
    { slug: "loegeringe-i-bobledej", label: "Løgringe i bobledej" },
    { slug: "sprode-foraarsruller-med-bobler", label: "Sprøde forårsruller" },
    { slug: "kartoffelchips-med-stenbiderrogn", label: "Chips med stenbiderrogn" },
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
    { slug: "fish-and-chips", label: "Fish & chips" },
  ],
  "hverdags-bobler": [
    { slug: "fried-chicken-med-bobler", label: "Fried chicken" },
    { slug: "hotdogs-med-cava", label: "Hotdogs med Cava" },
    { slug: "flaesketestegssandwich-med-pet-nat", label: "Flæskestegssandwich" },
    { slug: "smash-burger-med-troffelmayo", label: "Smash burger" },
    { slug: "luksus-nachos-med-cava", label: "Nachos med Cava" },
    { slug: "gougeres", label: "Gougères" },
    { slug: "cava-svamperisotto", label: "Cava-svamperisotto" },
    { slug: "champagne-brioche", label: "Champagne-brioche" },
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med mousserende sabayon" },
    { slug: "moscato-dasti-sorbet", label: "Moscato d'Asti-sorbet" },
    { slug: "fish-and-chips", label: "Fish & chips" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Mousserende vinsmarinade" },
  ],
  "hverdagsbobler-under-100-til-mad": [
    { slug: "fried-chicken-med-bobler", label: "Fried chicken" },
    { slug: "hotdogs-med-cava", label: "Hotdogs med Cava" },
    { slug: "luksus-nachos-med-cava", label: "Nachos med Cava" },
  ],
  "bobler-til-takeaway-og-fastfood": [
    { slug: "fried-chicken-med-bobler", label: "Fried chicken" },
    { slug: "pizza-bianca-mousserende-rose", label: "Pizza bianca" },
    { slug: "sprode-foraarsruller-med-bobler", label: "Forårsruller" },
  ],
  "pet-nat-for-begyndere": [
    { slug: "flaesketestegssandwich-med-pet-nat", label: "Flæskestegssandwich med pét-nat" },
  ],
  "rosevin-med-bobler": [
    { slug: "pizza-bianca-mousserende-rose", label: "Pizza bianca med mousserende rosé" },
  ],
  "bedste-champagne-under-300-kr": [
    { slug: "smash-burger-med-troffelmayo", label: "Smash burger med trøffelmayo" },
  ],
  "fibermaxxing-vinost-gront": [
    { slug: "rodvinsstuvet-gronkaal-med-valnodder", label: "Rødvinsstuvet grønkål" },
    { slug: "puy-linser-i-rodvin-med-chokolade", label: "Puy-linser med chokolade" },
    { slug: "byg-otto-med-hvidvin-og-svampe", label: "Byg-otto med svampe" },
    { slug: "braiseret-spidskaal-i-hvidvin", label: "Braiseret spidskål" },
    { slug: "belugalinser-i-rodvin", label: "Belugalinser i rødvin" },
    { slug: "hvidvins-confiterede-portobellos", label: "Confiterede portobellos" },
    { slug: "raamarineret-spidskaalssalat", label: "Råmarineret spidskålssalat" },
    { slug: "fuldkorns-taralli-med-hvidvin", label: "Fuldkorns-taralli" },
    { slug: "grov-focaccia-med-hvidvin", label: "Grov focaccia" },
  ],
  "umami-uden-koed-vin": [
    { slug: "svampe-bourguignon-med-jordskokkechips", label: "Svampe Bourguignon med jordskokke" },
    { slug: "puy-linser-i-rodvin-med-chokolade", label: "Puy-linser" },
    { slug: "kikaerte-cassoulet-med-hvidvin", label: "Kikærte-cassoulet" },
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "hvidvins-confiterede-portobellos", label: "Confiterede portobellos" },
    { slug: "broccolisalat-med-portvins-baconjam", label: "Broccolisalat med baconjam" },
  ],
  "vin-til-crunch": [
    { slug: "hvidvinsbraiserede-porrer-med-panko", label: "Porrer med panko" },
    { slug: "grillet-blomkaalssteak-med-rodvinssauce", label: "Blomkålssteak" },
    { slug: "lynstegt-palmekaal-med-sherry-sennepsfro", label: "Palmekål med sennepsfrø" },
    { slug: "svampe-bourguignon-med-jordskokkechips", label: "Bourguignon med chips" },
    { slug: "raamarineret-spidskaalssalat", label: "Spidskålssalat" },
    { slug: "sprodstegte-oestershatte-med-bearnaise", label: "Sprøde østershatte" },
    { slug: "hvidvinssyltede-sennepsfro", label: "Hvidvinssyltede sennepsfrø" },
    { slug: "ristede-graeskarkerner-i-rodvinssalt", label: "Græskarkerner i rødvinssalt" },
    { slug: "fuldkorns-taralli-med-hvidvin", label: "Fuldkorns-taralli" },
  ],
  "vinost-pantry-5-flasker": [
    { slug: "rodvinssauce-essens", label: "Rødvinssauce-essens" },
    { slug: "hvidvins-bearnaiseessens", label: "Béarnaiseessens" },
    { slug: "rodvinssennep", label: "Rødvinssennep" },
    { slug: "glace-de-viande-med-rodvin", label: "Glace de viande" },
    { slug: "portvins-baconmarmelade", label: "Portvins-baconmarmelade" },
    { slug: "hvidvins-hvidloegsconfit", label: "Hvidløgsconfit" },
    { slug: "sherrysyltede-sennepsfro", label: "Sherrysyltede sennepsfrø" },
    { slug: "hvidvins-jalapenorelish", label: "Jalapeñorelish" },
    { slug: "aegte-teriyakisauce", label: "Ægte teriyaki" },
    { slug: "rose-hindbaercoulis", label: "Rosé-hindbærcoulis" },
    { slug: "espresso-marsalasirup", label: "Espresso-Marsalasirup" },
    { slug: "champagne-jordbaersirup", label: "Champagne-jordbærsirup" },
  ],
  "vin-som-naturlig-smagsforstaerker": [
    { slug: "rodvinssauce-essens", label: "Rødvinssauce-essens" },
    { slug: "glace-de-viande-med-rodvin", label: "Glace de viande" },
    { slug: "hvidvins-bearnaiseessens", label: "Béarnaiseessens" },
  ],
  "byg-din-egen-eddikemor": [
    { slug: "hindbaer-rodvinseddike", label: "Hindbær-rødvinseddike" },
    { slug: "hvidvinssyltede-gronne-tomater", label: "Hvidvinssyltede grønne tomater" },
    { slug: "sherrysyltede-sennepsfro", label: "Sherrysyltede sennepsfrø" },
  ],
  "naturlig-konservering-med-vin-og-eddike": [
    { slug: "hindbaer-rodvinseddike", label: "Hindbær-rødvinseddike" },
    { slug: "hvidvinssyltede-gronne-tomater", label: "Syltede grønne tomater" },
    { slug: "rodvinssennep", label: "Rødvinssennep" },
    { slug: "hvidvins-jalapenorelish", label: "Jalapeñorelish" },
    { slug: "rodvinssirup-med-vanilje", label: "Rødvinssirup" },
  ],
  "kemien-i-marinering-med-vin": [
    { slug: "hvidvins-bearnaiseessens", label: "Béarnaiseessens (reduktion)" },
    { slug: "rodvinssauce-essens", label: "Rødvinssauce-essens" },
  ],

};
