/** Guide → opskrifter med vin i gryden (intern linking). */
export const GUIDE_RECIPE_LINKS: Record<string, readonly { slug: string; label: string }[]> = {
  "vin-til-tapas": [
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "champignons-al-ajillo-med-hvidvin", label: "Champignons al ajillo" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
    { slug: "spansk-koedboller-i-rodvinsauce", label: "Almóndigas i rødvinsauce" },
    { slug: "syltede-roedloeg-med-hvidvin", label: "Syltede rødløg med hvidvin" },
    { slug: "roedvinsgele-til-charcuteri", label: "Rødvinsgelé til charcuteri" },
  ],
  "vin-til-gryderet": [
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "boeuf-bourguignon", label: "Boeuf bourguignon" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
    { slug: "braiseret-oksekaebe-med-rodvin", label: "Braiseret oksekaebe" },
    { slug: "svinekaebber-i-rodvinssky", label: "Svinekæber i rødvinssky" },
    { slug: "estofado-oksestuvning-i-rodvin", label: "Estofado" },
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
  ],
  "vin-til-suppe": [
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "tomatsuppe-med-hvidvin", label: "Tomatsuppe med hvidvin" },
    { slug: "loegsuppe-med-hvidvin", label: "Løgsuppe med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
  ],
  "vin-til-tarteletter": [
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
  ],
  "vin-til-pizza-og-pasta": [
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
  ],
  "rodvin-til-pizza": [
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin til pizza" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
  ],
  "vin-til-nytaar-og-nytaarsmenu": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
  ],
  "vin-til-lasagne": [
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin i kødsovs" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
  ],
  "vin-til-pizza": [
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin (samme sovs-logik)" },
  ],
  "vin-til-julefrokost": [
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
    { slug: "flaesketesteg-med-rodvin-i-brun-sovs", label: "Flæskesteg med rødvin" },
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
    { slug: "groenlangkaal-med-hvidvin", label: "Grønlangkål med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
  ],
  "vin-til-fisk-og-skaldyr": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "rodspette-med-hvidvin", label: "Rødspætte med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "fisk-i-hvidvinsauce", label: "Fisk i hvidvinsauce" },
    { slug: "torsk-i-hvidvin", label: "Torsk i hvidvin" },
  ],
  "vin-til-boeff": [
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
  ],
  "vin-til-grill-og-bbq": [
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
  ],
  "vin-til-kartoffelmad": [
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
  ],
  "vin-til-italiensk-mad": [
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
  ],
  "vin-til-spansk-mad": [
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
    { slug: "paella-med-hvidvin", label: "Paella med hvidvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
  ],
  "vin-til-wok": [
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
  ],
  "vin-til-oksekoed": [
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "hakkeboef-i-rodvinssauce", label: "Hakkebøf i rødvinsauce" },
  ],
  "vin-til-lam": [
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
  ],
  "vin-til-svinekoed": [
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "svinefilet-i-rodvinssauce", label: "Svinefilet i rødvinsauce" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
  ],
  "sangiovese-til-pasta": [
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
  ],
  "vin-til-kylling-og-lyst-koed": [
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "kyllingefilet-i-rodvin-med-svampe", label: "Kyllingefilet i rødvin" },
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "citronkylling-i-hvidvin", label: "Citronkylling i hvidvin" },
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
  ],
  "vin-til-vegetar-og-gront": [
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
    { slug: "ratatouille-med-hvidvin", label: "Ratatouille med hvidvin" },
  ],
};
