/** Guide → opskrifter med vin i gryden (intern linking). */
export const GUIDE_RECIPE_LINKS: Record<string, readonly { slug: string; label: string }[]> = {
  "vin-til-tapas": [
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "champignons-al-ajillo-med-hvidvin", label: "Champignons al ajillo" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
    { slug: "spansk-koedboller-i-rodvinsauce", label: "Almóndigas i rødvinsauce" },
    { slug: "syltede-roedloeg-med-hvidvin", label: "Syltede rødløg med hvidvin" },
    { slug: "roedvinsgele-til-charcuteri", label: "Rødvinsgelé til charcuteri" },
    { slug: "chimichurri-med-rodvin", label: "Chimichurri med rødvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "hummus-med-hvidvin", label: "Hummus med hvidvin" },
    { slug: "aioli-med-hvidvin", label: "Aioli med hvidvin" },
    { slug: "marinerede-oliven-med-hvidvin", label: "Marinerede oliven med hvidvin" },
    { slug: "kamskjell-med-hvidvin", label: "Kamskjell med hvidvin" },
    { slug: "portvins-fignemarmelade-med-rosmarin", label: "Portvins-fignemarmelade" },
    { slug: "rose-syltede-roedloeg-med-timian", label: "Rosé-syltede rødløg" },
    { slug: "bagt-camembert-med-hvidvin", label: "Bagt camembert med hvidvin" },
    { slug: "manchego-marineret-i-hvidvin", label: "Manchego marineret i hvidvin" },
    { slug: "portvinsglaserede-dadler-med-bacon", label: "Portvinsglaserede dadler" },
    { slug: "kaemperejer-dampet-i-hvidvin", label: "Dampede kæmperejer i hvidvin" },
    { slug: "serrano-med-hvidvinsmarineret-melon", label: "Serrano med hvidvinsmelon" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
  ],
  "vin-til-gryderet": [
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "boeuf-bourguignon", label: "Boeuf bourguignon" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
    { slug: "braiseret-oksekaebe-med-rodvin", label: "Braiseret oksekaebe" },
    { slug: "svinekaebber-i-rodvinssky", label: "Svinekæber i rødvinssky" },
    { slug: "estofado-oksestuvning-i-rodvin", label: "Estofado" },
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
    { slug: "cassoulet-med-rodvin", label: "Cassoulet med rødvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
    { slug: "feijoada-med-rodvin", label: "Feijoada med rødvin" },
    { slug: "bigos-med-rodvin", label: "Bigos med rødvin" },
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "morbradgryde-med-hvidvin", label: "Mørbradgryde med hvidvin" },
    { slug: "biksemad-med-rodvin", label: "Biksemad med rødvin" },
    { slug: "svinekaeber-i-rodvin-og-moerkt-oel", label: "Svinekæber i rødvin og mørkt øl" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin (Lapin au Vin Blanc)" },
  ],
  "vin-til-suppe": [
    { slug: "oksesuppe-med-rodvin", label: "Oksesuppe med rødvin" },
    { slug: "tomatsuppe-med-hvidvin", label: "Tomatsuppe med hvidvin" },
    { slug: "loegsuppe-med-hvidvin", label: "Løgsuppe med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
    { slug: "caldeirada-med-hvidvin", label: "Caldeirada med hvidvin" },
    { slug: "krebsesuppe-med-hvidvin", label: "Krebsesuppe med hvidvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Jordskokkesuppe med hvidvinsreduktion" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone med hvidvin" },
  ],
  "vin-til-tarteletter": [
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "vol-au-vent-med-hvidvin", label: "Vol-au-vent med hvidvin" },
  ],
  "vin-til-pizza-og-pasta": [
    { slug: "klassisk-lasagne", label: "Klassisk lasagne (vin til glasset)" },
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "pesto-med-hvidvin", label: "Pesto med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "pesto-pasta-hvidvin", label: "Pesto-pasta med hvidvin" },
  ],
  "rodvin-til-pizza": [
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin til pizza" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
  ],
  "vin-til-nytaar-og-nytaarsmenu": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "figner-og-dadler-i-rodvin", label: "Figner og dadler i rødvin" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
  ],
  "vin-til-lasagne": [
    { slug: "klassisk-lasagne", label: "Klassisk lasagne (vin til glasset)" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin i kødsovs" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
  ],
  "vin-til-pizza": [
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin til pizza" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "pizza-parmaskinke-og-rucola", label: "Pizza med parma og rucola" },
  ],
  "vin-til-julefrokost": [
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
    { slug: "flaesketesteg-med-rodvin-i-brun-sovs", label: "Flæskesteg med rødvin" },
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
    { slug: "groenlangkaal-med-hvidvin", label: "Grønlangkål med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "risalamande-med-hvidvin", label: "Risalamande med hvidvin" },
    { slug: "aeblekage-hvidvin-karamel", label: "Æblekage med hvidvin-karamel" },
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-fisk-og-skaldyr": [
    { slug: "gravad-laks-med-hvidvin", label: "Gravad laks med hvidvin" },
    { slug: "rodspette-med-hvidvin", label: "Rødspætte med hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
    { slug: "fisk-i-hvidvinsauce", label: "Fisk i hvidvinsauce" },
    { slug: "torsk-i-hvidvin", label: "Torsk i hvidvin" },
    { slug: "muslinger-i-hvidvin", label: "Muslinger i hvidvin" },
    { slug: "bouillabaisse-med-hvidvin", label: "Bouillabaisse med hvidvin" },
    { slug: "caldeirada-med-hvidvin", label: "Caldeirada med hvidvin" },
    { slug: "aioli-med-hvidvin", label: "Aioli med hvidvin" },
    { slug: "helleflynder-med-hvidvin", label: "Helleflynder med hvidvin" },
    { slug: "krebsesuppe-med-hvidvin", label: "Krebsesuppe med hvidvin" },
    { slug: "kamskjell-med-hvidvin", label: "Kamskjell med hvidvin" },
    { slug: "oesters-gratineret-med-hvidvin", label: "Østers gratineret med hvidvin" },
    { slug: "lakse-rilette-med-hvidvin", label: "Lakse-rilette med hvidvin" },
    { slug: "blaeksprutteringe-i-hvidvin", label: "Blæksprutteringe i hvidvin" },
    { slug: "pighvar-med-hvidvin-og-vesterhavsost", label: "Pighvar med hvidvin og Vesterhavsost" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
  ],
  "vin-til-boeff": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "balsamico-rodvinsglaserede-skalotteloeg", label: "Balsamico-rødvinsglaserede skalotteløg" },
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Klassisk rødvins-rosmarinmarinade" },
    { slug: "syrlig-rodvin-balsamicomarinade", label: "Syrlig rødvin-balsamicomarinade" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico- og rødvinssirup til steak" },
  ],
  "vin-til-oksefilet": [
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "balsamico-rodvinsmarineret-oksemoerbrad", label: "Balsamico-rødvinsmarineret oksemørbrad" },
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce til oksemørbrad" },
  ],
  "vin-til-peberboef": [
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinssauce" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
  ],
  "vin-til-pulled-pork": [
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "svinebryst-braiseret-i-rodvin", label: "Svinebryst braiseret i rødvin" },
  ],
  "vin-til-butter-chicken": [
    { slug: "butter-chicken", label: "Butter chicken (vin til glasset)" },
    { slug: "butter-chicken-med-hvidvin", label: "Butter chicken med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "thai-gron-karry-med-hvidvin", label: "Thai grøn karry med hvidvin" },
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
  ],
  "vin-til-dyreryg": [
    { slug: "fasan-med-rodvin", label: "Fasan med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
  ],
  "vin-til-kalvemoerbrad": [
    { slug: "kalv-i-hvidvinsauce", label: "Kalv i hvidvinsauce" },
    { slug: "blanquette-de-veau-med-hvidvin", label: "Blanquette de veau" },
    { slug: "ossobuco-med-hvidvin", label: "Ossobuco med hvidvin" },
    { slug: "saltimbocca-alla-romana", label: "Saltimbocca alla Romana" },
  ],
  "vin-til-svinemoerbrad": [
    { slug: "svinefilet-i-rodvinssauce", label: "Svinefilet i rødvinssauce" },
    { slug: "karbonader-i-hvidvinsauce", label: "Karbonader i hvidvinsauce" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "morbradgryde-med-paprika-og-hvidvin", label: "Mørbradgryde med paprika og hvidvin" },
    { slug: "hvidvins-sennepsmarinade", label: "Hvidvins-sennepsmarinade" },
  ],
  "vin-til-ribeye": [
    { slug: "ribeye", label: "Ribeye (vin til glasset)" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
  ],
  "vin-til-roastbeef": [
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
  ],
  "vin-til-boef-stroganoff": [
    { slug: "boef-stroganoff-med-hvidvin", label: "Bøf stroganoff med hvidvin" },
    { slug: "svampesovs-med-hvidvin", label: "Svampesovs med hvidvin" },
    { slug: "boef-stroganoff-med-rodvin", label: "Boeuf Stroganoff med rødvin" },
  ],
  "vin-til-bearnaise": [
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "roedvinssauce-til-boef", label: "Rødvinsauce til bøf" },
  ],
  "vin-til-stjerneskud": [
    { slug: "rejer-i-hvidvin", label: "Gambas al ajillo" },
    { slug: "fiskefilet-citron-hvidvin", label: "Fiskefilet med citron og hvidvin" },
    { slug: "fiskefrikadeller-i-hvidvinsauce", label: "Fiskefrikadeller i hvidvinsauce" },
  ],
  "vin-til-grill-og-bbq": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
    { slug: "chimichurri-med-rodvin", label: "Chimichurri med rødvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvins-rosmarinmarinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "provencal-hvidvins-hvidloegsmarinade", label: "Provence-kylling" },
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
  ],
  "vin-til-kartoffelmad": [
    { slug: "kartoffelgratin-med-hvidvin", label: "Kartoffelgratin med hvidvin" },
    { slug: "kartoffelmos-med-hvidvin", label: "Kartoffelmos med hvidvin" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-italiensk-mad": [
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "kylling-piccata-med-hvidvin", label: "Kylling piccata med hvidvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "lasagne-med-rodvin", label: "Lasagne med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "pesto-med-hvidvin", label: "Pesto med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "carpaccio-med-hvidvindressing", label: "Carpaccio med hvidvindressing" },
    { slug: "tiramisu-med-marsala-og-hvidvin", label: "Tiramisu med marsala og hvidvin" },
    { slug: "panna-cotta-med-hvidvin", label: "Panna cotta med hvidvin" },
    { slug: "ossobuco-med-rodvin", label: "Ossobuco med rødvin og gremolata" },
    { slug: "saltimbocca-alla-romana", label: "Saltimbocca alla Romana" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone di Verdure" },
  ],
  "vin-til-spansk-mad": [
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
    { slug: "paella-med-hvidvin", label: "Paella med hvidvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino" },
    { slug: "sangria-med-rodvin", label: "Sangria med rødvin" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
  ],
  "vin-til-wok": [
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
    { slug: "wok-rejer-hvidvin", label: "Wok-rejer med hvidvin" },
  ],
  "vin-til-oksekoed": [
    { slug: "rodvinsmarinade-til-oksekod", label: "Rødvinsmarinade til oksekød" },
    { slug: "oksesteg-med-rodvin", label: "Oksesteg med rødvin" },
    { slug: "entrecote-med-rodvinsmarinade", label: "Entrecôte med rødvinsmarinade" },
    { slug: "cote-de-boeuf-med-rodvin", label: "Côte de bœuf med rødvin" },
    { slug: "peberboef-med-rodvinsauce", label: "Peberbøf med rødvinsauce" },
    { slug: "hakkeboef-i-rodvinssauce", label: "Hakkebøf i rødvinsauce" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "biksemad-med-rodvin", label: "Biksemad med rødvin" },
    { slug: "oksehojreb-marineret-i-rodvin", label: "Oksehøjreb marineret i rødvin" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvins-rosmarinmarinade" },
    { slug: "portvins-hvidloegsmarinade", label: "Portvins-hvidløgsmarinade" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
    { slug: "syrlig-rodvin-balsamicomarinade", label: "Syrlig balsamicomarinade" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico- og rødvinssirup til steak" },
  ],
  "vin-til-lam": [
    { slug: "lammesteg-med-rodvin-rosmarin", label: "Lammesteg med rødvin og rosmarin" },
    { slug: "lammekoteletter-i-rodvin", label: "Lammekoteletter i rødvin" },
    { slug: "braiseret-lammeskank-med-rodvin", label: "Braiseret lammeskank" },
    { slug: "lammegryde-mynte-hvidvin", label: "Lammegryde med mynte og hvidvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
    { slug: "portvin-mynte-lammemarinade", label: "Port-mynte-lam" },
    { slug: "rodvin-hvidloeg-rosmarinmarinade-til-lam", label: "Rosmarin til lam" },
  ],
  "vin-til-svinekoed": [
    { slug: "svinekam-med-rodvin", label: "Svinekam med rødvin" },
    { slug: "svineribs-med-rodvin", label: "Svineribs med rødvin" },
    { slug: "svinefilet-i-rodvinssauce", label: "Svinefilet i rødvinsauce" },
    { slug: "porchetta-med-hvidvin", label: "Porchetta med hvidvin" },
    { slug: "svinebryst-braiseret-i-rodvin", label: "Svinebryst braiseret i rødvin" },
    { slug: "morbradgryde-med-hvidvin", label: "Mørbradgryde med hvidvin" },
    { slug: "svinekaeber-i-portvinsreduktion", label: "Svinekæber i portvinsreduktion" },
    { slug: "glaseret-skinke-med-madeirasauce", label: "Glaseret skinke med Madeirasauce" },
    { slug: "morbradgryde-med-paprika-og-hvidvin", label: "Mørbradgryde med paprika" },
    { slug: "svinekoteletter-med-sennep-og-hvidvin", label: "Svinekoteletter med sennep og hvidvin" },
    { slug: "hvidvins-sennepsmarinade", label: "Hvidvins-sennepsmarinade" },
    { slug: "sherry-appelsinmarinade", label: "Sherry-appelsinmarinade" },
    { slug: "italiensk-hvidvins-salviemarinade", label: "Salviemarinade" },
    { slug: "rodvins-paprikamarinade", label: "Rødvins-paprikamarinade" },
    { slug: "hvidvins-citron-oreganomarinade", label: "Citron-oreganomarinade" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
  ],
  "sangiovese-til-pasta": [
    { slug: "pasta-amatriciana-med-rodvin", label: "Pasta amatriciana med rødvin" },
    { slug: "pasta-puttanesca-med-rodvin", label: "Pasta puttanesca med rødvin" },
    { slug: "bolognese-med-rodvin", label: "Bolognese med rødvin" },
    { slug: "ragu-med-rodvin", label: "Ragù med rødvin" },
    { slug: "tomatsauce-med-rodvin-til-pizza", label: "Tomatsauce med rødvin" },
  ],
  "vin-til-kylling-og-lyst-koed": [
    { slug: "kylling-piccata-med-hvidvin", label: "Kylling piccata med hvidvin" },
    { slug: "braiseret-kylling-med-rodvin", label: "Braiseret kylling med rødvin" },
    { slug: "fennikelkylling-med-hvidvin", label: "Fennikelkylling med hvidvin" },
    { slug: "stuvet-kylling-med-hvidvin", label: "Stuvet kylling med hvidvin" },
    { slug: "kyllingesuppe-med-hvidvin", label: "Kyllingesuppe med hvidvin" },
    { slug: "kyllingefilet-i-rodvin-med-svampe", label: "Kyllingefilet i rødvin" },
    { slug: "coq-au-vin", label: "Coq au vin" },
    { slug: "citronkylling-i-hvidvin", label: "Citronkylling i hvidvin" },
    { slug: "wok-kylling-med-hvidvin", label: "Wok-kylling med hvidvin" },
    { slug: "tarteletter-i-hvidvin", label: "Tarteletter i hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
    { slug: "poulet-a-lestragon", label: "Poulet à l'Estragon" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin" },
    { slug: "kylling-i-hvidvinssauce-med-porrer-og-vindruer", label: "Kylling med porrer og vindruer" },
    { slug: "kylling-teriyaki-med-sake-og-mirin", label: "Kylling Teriyaki" },
    { slug: "provencal-hvidvins-hvidloegsmarinade", label: "Provencalsk marinade" },
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
    { slug: "marsala-svampemarinade", label: "Marsala-svampe" },
    { slug: "hvidvins-estragonmarinade", label: "Estragonmarinade" },
    { slug: "hvidvins-karrymarinade", label: "Karrymarinade" },
    { slug: "hvidvins-estragonglace-til-kylling", label: "Hvidvins-estragonglace til kylling" },
  ],
  "vin-til-vegetar-og-gront": [
    { slug: "champignonsuppe-med-hvidvin", label: "Champignonsuppe med hvidvin" },
    { slug: "sellerisuppe-med-hvidvin", label: "Sellerisuppe med hvidvin" },
    { slug: "ratatouille-med-hvidvin", label: "Ratatouille med hvidvin" },
    { slug: "vegetar-gryderet-rodvin", label: "Vegetar-gryderet med rødvin" },
    { slug: "shakshuka-med-hvidvin", label: "Shakshuka med hvidvin" },
    { slug: "hummus-med-hvidvin", label: "Hummus med hvidvin" },
    { slug: "romesco-med-rodvin", label: "Romesco med rødvin" },
    { slug: "marinerede-oliven-med-hvidvin", label: "Marinerede oliven med hvidvin" },
    { slug: "caponata-med-rodvin", label: "Caponata med rødvin" },
    { slug: "minestrone-med-rodvin", label: "Minestrone med rødvin" },
    { slug: "bagt-graeskar-med-salviesmoer", label: "Bagt græskar med salviesmør" },
    { slug: "svampetoast-med-hvidvin-og-timian", label: "Svampetoast med hvidvin" },
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Jordskokkesuppe" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
  ],
  "vin-til-nachos": [
    { slug: "nachos-med-rodvinskaesesovs", label: "Nachos med rødvinskaesesovs" },
  ],
  "vin-til-kebab-og-shawarma": [
    { slug: "shawarma-tallerken", label: "Shawarma-tallerken (vin til glasset)" },
    { slug: "shawarma-kylling-med-hvidvin", label: "Shawarma-kylling med hvidvin" },
    { slug: "kebab-spyd-med-rodvin", label: "Kebab-spyd med rødvin" },
  ],
  "vin-til-burger": [
    { slug: "burger-med-rodvinsglace", label: "Gourmet-burger med rødvinssautérede løg" },
    { slug: "rodvins-loegkompot", label: "Rødvins-løgkompot" },
    { slug: "portvins-baconmarmelade", label: "Portvins-baconmarmelade" },
    { slug: "hvidvins-jalapenorelish", label: "Hvidvins-jalapeñorelish" },
    { slug: "oel-rodvinssennep", label: "Øl- og rødvinssennep" },
  ],
  "vin-til-pho": [
    { slug: "pho-kylling-med-hvidvin", label: "Pho med kylling og hvidvin" },
  ],
  "vin-til-ramen": [
    { slug: "ramen-kylling-med-hvidvin", label: "Ramen med kylling og hvidvin" },
  ],
  "vin-til-tacos": [
    { slug: "tacos-med-oksekoed", label: "Tacos med oksekød (vin til glasset)" },
    { slug: "tacos-med-rodvin-okse", label: "Tacos med okse og rødvin" },
  ],
  "vin-til-karryretter": [
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
    { slug: "hvidvins-karrymarinade", label: "Hvidvins-karry" },
  ],
  "vin-til-ceviche": [
    { slug: "ceviche-med-hvidvin", label: "Ceviche med hvidvin" },
  ],
  "vin-til-quiche": [
    { slug: "quiche-med-hvidvin", label: "Quiche med hvidvin" },
  ],
  "vin-til-sild": [
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "stegte-sild-i-hvidvin", label: "Stegte sild i hvidvin" },
  ],
  "vin-til-falafel-og-hummus": [
    { slug: "falafel-tallerken", label: "Falafel-tallerken (vin til glasset)" },
    { slug: "falafel-tallerken-med-hvidvin", label: "Falafel-tallerken med hvidvin" },
  ],
  "vin-til-asiatisk-mad": [
    { slug: "pad-thai-med-hvidvin", label: "Pad thai med hvidvin" },
    { slug: "dim-sum-kylling-hvidvin", label: "Dim sum med kylling og hvidvin" },
    { slug: "couscous-kylling-med-hvidvin", label: "Couscous med kylling og hvidvin" },
    { slug: "pho-kylling-med-hvidvin", label: "Pho med kylling og hvidvin" },
    { slug: "ramen-kylling-med-hvidvin", label: "Ramen med kylling og hvidvin" },
    { slug: "sticky-pork-belly-med-shaoxing", label: "Sticky pork belly med Shaoxing" },
    { slug: "rosenkaal-med-hvidvin-og-oestersauce", label: "Rosenkål med hvidvin og østerssauce" },
    { slug: "asiatisk-rodvin-ingefaermarinade", label: "Asiatisk rødvin-ingefærmarinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "hvidvins-karrymarinade", label: "Karrymarinade" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Shaoxing" },
  ],
  "vin-til-laks": [
    { slug: "grillet-laks-hvidvin-dressing", label: "Grillet laks med hvidvindressing" },
    { slug: "dampet-laks-med-rosevinssauce", label: "Dampet laks med rosévinssauce" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
    { slug: "hvidvins-dildmarinade", label: "Dildmarinade" },
  ],
  "vin-til-sushi": [
    { slug: "dim-sum-kylling-hvidvin", label: "Dim sum med kylling og hvidvin" },
  ],
  "vin-til-stegt-flaesk": [
    { slug: "stegt-flaesk-med-persillesovs", label: "Stegt flæsk med persillesovs (vin til glasset)" },
    { slug: "stegt-flaesk-i-hvidvinsauce", label: "Stegt flæsk i hvidvinsauce" },
    { slug: "persillesovs-med-hvidvin", label: "Persillesovs med hvidvin" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
  ],
  "vin-til-smorrebrod": [
    { slug: "sild-i-hvidvinseddike", label: "Sild i hvidvinseddike" },
    { slug: "stegte-sild-i-hvidvin", label: "Stegte sild i hvidvin" },
    { slug: "aebleflaesk-med-hvidvin", label: "Æbleflæsk med hvidvin" },
    { slug: "frikadeller-i-hvidvinsauce", label: "Frikadeller i hvidvinsauce" },
    { slug: "rejesalat-med-hvidvin", label: "Rejesalat med hvidvin" },
    { slug: "oel-rodvinssennep", label: "Øl- og rødvinssennep" },
    { slug: "hvidvins-jalapenorelish", label: "Hvidvins-jalapeñorelish" },
    { slug: "hvidvinssyltede-agurker-med-dild", label: "Hvidvinssyltede agurker med dild" },
    { slug: "sherrysyltede-sennepsfro", label: "Sherrysyltede sennepsfrø" },
    { slug: "hvidvinssyltede-gronne-tomater", label: "Hvidvinssyltede grønne tomater" },
  ],
  "vin-til-rejer": [
    { slug: "rejesalat-med-hvidvin", label: "Rejesalat med hvidvin" },
    { slug: "rejer-i-hvidvin", label: "Gambas al ajillo" },
    { slug: "wok-rejer-hvidvin", label: "Wok-rejer med hvidvin" },
    { slug: "kaemperejer-dampet-i-hvidvin", label: "Dampede kæmperejer i hvidvin" },
    { slug: "gambas-al-jerez", label: "Gambas al Jerez" },
    { slug: "ingefaer-chili-hvidvinsmarinade", label: "Ingefær-chili" },
  ],
  "vin-til-koldskaal": [
    { slug: "koldskal-med-hvidvin", label: "Koldskål med hvidvin" },
  ],
  "vin-til-flaesketesteg": [
    { slug: "flaesketesteg-med-rodvin-i-brun-sovs", label: "Flæskesteg med rødvin i brun sovs" },
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "aeble-hvidvinskompot-med-timian", label: "Æble- og hvidvinskompot med timian" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
  ],
  "vin-til-graesk-mad": [
    { slug: "moussaka-med-rodvin", label: "Moussaka med rødvin" },
    { slug: "paella-med-hvidvin", label: "Paella med hvidvin" },
    { slug: "chorizo-i-rodvin", label: "Chorizo al vino (tapas-stil)" },
    { slug: "souvlaki-med-hvidvin", label: "Souvlaki med hvidvin" },
  ],
  "vin-til-mortensaften": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
    { slug: "roedkaal-med-rodvin", label: "Rødkål med rødvin" },
    { slug: "brune-kartoffler-med-rodvin", label: "Brune kartoffler med rødvin" },
  ],
  "vin-til-poelser-og-kartoffel": [
    { slug: "poelser-i-rodvinsglace", label: "Pølser i rødvinsglace" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
  ],
  "vin-til-salat": [
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
  ],
  "vin-til-roedgroed": [
    { slug: "roedgroed-med-portvin", label: "Rødgrød med portvin" },
  ],
  "vin-til-kalkun": [
    { slug: "kalkunsteg-med-hvidvin", label: "Kalkunsteg med hvidvin" },
    { slug: "hvidvins-estragonmarinade", label: "Estragon til fjerkræ" },
  ],
  "vin-til-hummer": [
    { slug: "hummer-i-hvidvinsauce", label: "Hummer i hvidvinsauce" },
    { slug: "grillede-jomfruhummere-med-hvidloegssmoer", label: "Grillede jomfruhummere" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque med cognac og hvidvin" },
  ],
  "vin-til-paaske-og-paaskefrokost": [
    { slug: "lammesteg-med-rodvin-rosmarin", label: "Lammesteg med rødvin og rosmarin" },
  ],
  "vin-til-mexicansk-mad": [
    { slug: "enchiladas-med-rodvin", label: "Enchiladas med rødvin" },
    { slug: "chili-lime-hvidvinsmarinade", label: "Chili-lime-marinade" },
  ],
  "vin-til-thai-mad": [
    { slug: "thai-gron-karry-med-hvidvin", label: "Thai grøn karry med hvidvin" },
    { slug: "tom-kha-gai-med-hvidvin", label: "Tom Kha Gai med hvidvin" },
  ],
  "vin-til-brittisk-mad": [
    { slug: "shepherd-pie-med-rodvin", label: "Shepherd's pie med rødvin" },
    { slug: "okse-wellington-med-rodvinssauce", label: "Okse-wellington med rødvinssauce" },
    { slug: "fish-and-chips-med-hvidvin", label: "Fish and chips med hvidvin" },
  ],
  "vin-til-vietnamesisk-mad": [
    { slug: "bun-cha-med-hvidvin", label: "Bun cha med hvidvin" },
  ],
  "vin-til-kinesisk-mad": [
    { slug: "kung-pao-kylling-med-hvidvin", label: "Kung pao kylling med hvidvin" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Femkrydderi" },
  ],
  "vin-til-spareribs": [
    { slug: "pulled-pork-med-rodvin", label: "Pulled pork med rødvin" },
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
  ],
  "vin-til-aebleskiver": [
    { slug: "aebleskiver-med-hvidvin", label: "Æbleskiver med hvidvin" },
  ],
  "vin-til-frikadeller": [
    { slug: "frikadeller-med-kartofler", label: "Frikadeller med kartofler (vin til glasset)" },
    { slug: "frikadeller-i-hvidvinsauce", label: "Frikadeller i hvidvinsauce" },
    { slug: "karbonader-i-hvidvinsauce", label: "Karbonader i hvidvinsauce" },
  ],
  "vin-til-torsk": [
    { slug: "torsk-i-rodvinsauce", label: "Torsk i rødvinsauce" },
    { slug: "torsk-i-hvidvin", label: "Torsk i hvidvin" },
    { slug: "helleflynder-med-hvidvin", label: "Helleflynder med hvidvin" },
    { slug: "hvidvinsdampet-torsk-med-porrer-og-safran", label: "Hvidvinsdampet torsk med porrer og safran" },
    { slug: "hvidvinsdampet-torsk-en-papillote", label: "Hvidvinsdampet torsk en papillote" },
  ],
  "vin-til-moussaka": [
    { slug: "moussaka-med-rodvin", label: "Moussaka med rødvin" },
  ],
  "vin-til-carbonara": [
    { slug: "carbonara-med-hvidvin", label: "Carbonara med hvidvin" },
  ],
  "vin-til-risotto": [
    { slug: "risotto-med-hvidvin", label: "Risotto med hvidvin" },
    { slug: "skaldyrsrisotto-med-hvidvin", label: "Skaldyrsrisotto med hvidvin" },
  ],
  "vin-til-paella": [
    { slug: "paella-med-rodvin", label: "Paella med rødvin" },
  ],
  "vin-til-chili-con-carne": [
    { slug: "chili-con-carne-med-rodvin", label: "Chili con carne med rødvin" },
  ],
  "vin-til-medister": [
    { slug: "medister-med-kartofler", label: "Medister med kartofler (vin til glasset)" },
    { slug: "medister-i-rodvinssauce", label: "Medister i rødvinsauce" },
  ],
  "vin-til-gulasch": [
    { slug: "gullasch-med-rodvin", label: "Gullasch med rødvin" },
    { slug: "gullaschsuppe-med-rodvin", label: "Gullaschsuppe med rødvin" },
    { slug: "bigos-med-rodvin", label: "Bigos med rødvin" },
  ],
  "vin-til-muslinger": [
    { slug: "muslinger-i-hvidvin", label: "Muslinger i hvidvin" },
    { slug: "muslinger-i-hvidvin-og-safran", label: "Muslinger i hvidvin og safran" },
    { slug: "zuppa-di-pesce", label: "Zuppa di Pesce" },
    { slug: "skaldyrsrisotto-med-hvidvin", label: "Skaldyrsrisotto" },
  ],
  "vin-til-blaeksprutte": [
    { slug: "blaeksprutte-i-rodvin", label: "Blæksprutte i rødvin" },
  ],
  "vin-til-fondue": [
    { slug: "fondue-med-hvidvin", label: "Fondue med hvidvin" },
  ],
  "vin-til-shakshuka": [
    { slug: "shakshuka-med-hvidvin", label: "Shakshuka med hvidvin" },
  ],
  "vin-til-and": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "andebaer-portvin-sauce", label: "Andebryst med portvinsauce" },
    { slug: "andeconfit-med-rodvin", label: "Andeconfit med rødvin" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
    { slug: "rodvinsmarineret-andebryst", label: "Rødvinsmarineret andebryst" },
    { slug: "andebryst-med-brombaer-rodvinssauce", label: "Andebryst med brombær-rødvinssauce" },
    { slug: "shaoxing-femkrydderi-marinade", label: "Shaoxing-and" },
    { slug: "aeble-hvidvinskompot-med-timian", label: "Æble- og hvidvinskompot med timian" },
  ],
  "vin-til-gas": [
    { slug: "andesteg-med-port-og-hvidvin", label: "Andesteg med port og hvidvin" },
    { slug: "andeconfit-med-rodvin", label: "Andeconfit med rødvin" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
  ],
  "vin-til-dessert-og-kransekage": [
    { slug: "paerer-i-rodvin", label: "Pærer i rødvin" },
    { slug: "aebletaerte-med-calvados-og-hvidvin", label: "Æbletærte med calvados og hvidvin" },
    { slug: "aeblekage-hvidvin-karamel", label: "Æblekage med hvidvin-karamel" },
    { slug: "zabaglione-med-hvidvin", label: "Zabaglione med hvidvin" },
    { slug: "tiramisu-med-marsala-og-hvidvin", label: "Tiramisu med marsala og hvidvin" },
    { slug: "creme-brulee-med-hvidvin", label: "Crème brûlée med hvidvin" },
    { slug: "panna-cotta-med-hvidvin", label: "Panna cotta med hvidvin" },
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
    { slug: "champagne-jordbaersorbet", label: "Champagne-jordbærsorbet" },
    { slug: "chokolade-trofler-med-portvin", label: "Chokoladetrøfler med portvin" },
    { slug: "hvidvinsbagede-fersken", label: "Hvidvinsbagede ferskner" },
    { slug: "rose-granite-med-hindbaer", label: "Rosé-granité med hindbær" },
    { slug: "mousserende-vingele-med-friske-baer", label: "Mousserende vingelé med bær" },
    { slug: "moscato-dasti-sorbet", label: "Moscato d'Asti sorbet" },
    { slug: "sherry-trifle", label: "Sherry Trifle" },
    { slug: "paerer-i-hvidvin-og-safran", label: "Pærer i hvidvin og safran" },
    { slug: "plommetrifli-med-rodvinssirup", label: "Plommetrifli med rødvinssirup" },
    { slug: "hvidvinsgele-med-sommerbaer", label: "Hvidvinsgelé med sommerbær" },
    { slug: "rodvinssorbet-med-brombaer", label: "Rødvinssorbet med brombær" },
    { slug: "tarte-tatin-med-hvidvinskaramel", label: "Tarte Tatin med hvidvinskaramel" },
    { slug: "moscato-pocherede-ferskner", label: "Moscato-pocherede ferskner" },
    { slug: "rodvinssirup-med-vanilje", label: "Rødvinssirup med vanilje" },
    { slug: "champagne-jordbaersirup", label: "Champagne- og jordbærsirup" },
    { slug: "rabarberkompot-med-rose", label: "Rabarberkompot med rosé" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
    { slug: "espresso-marsalasirup", label: "Espresso- og Marsalasirup" },
  ],
  "vin-til-brasiliansk-mad": [
    { slug: "feijoada-med-rodvin", label: "Feijoada med rødvin" },
  ],
  "vin-til-oesters": [
    { slug: "oesters-gratineret-med-hvidvin", label: "Østers gratineret med hvidvin" },
    { slug: "oesters-med-champagne-sabayonne", label: "Østers med Champagne-sabayonne" },
  ],
  "vin-til-klassisk-fransk-mad": [
    { slug: "bearnaisesauce-med-hvidvin", label: "Bearnaisesauce med hvidvin" },
    { slug: "asparges-i-hvidvinsauce", label: "Asparges i hvidvinsauce" },
    { slug: "canard-a-l-orange-med-rodvin", label: "Canard à l'orange med rødvin" },
    { slug: "blanquette-de-veau-med-hvidvin", label: "Blanquette de veau med hvidvin" },
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
  ],
  "vin-til-amerikansk-comfort-mad": [
    { slug: "brisket-braiseret-i-rodvin", label: "Brisket braiseret i rødvin" },
  ],
  "vin-til-tatar-og-carpaccio": [
    { slug: "carpaccio-med-hvidvindressing", label: "Carpaccio med hvidvindressing" },
    { slug: "boeftatar-med-hvidvin", label: "Bøftatar med hvidvin" },
  ],
  "vin-til-asparges": [
    { slug: "asparges-i-hvidvinsauce", label: "Asparges i hvidvinsauce" },
  ],
  "vin-i-cocktails-spritz-og-drikke": [
    { slug: "sangria-med-rodvin", label: "Sangria med rødvin" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "vin-til-indisk-mad": [
    { slug: "vindaloo-med-hvidvin", label: "Vindaloo med hvidvin" },
    { slug: "karrykylling-med-hvidvin", label: "Karrykylling med hvidvin" },
    { slug: "tikka-masala-med-hvidvin", label: "Tikka masala med hvidvin" },
  ],
  "vin-til-fisk-og-chips": [
    { slug: "fish-and-chips", label: "Fish and chips (vin til glasset)" },
    { slug: "fish-and-chips-med-hvidvin", label: "Fish and chips med hvidvin" },
  ],
  "vin-til-marokkansk-mad": [
    { slug: "marokkansk-kylling-tagine-med-hvidvin", label: "Marokkansk kylling tagine med hvidvin" },
    { slug: "lammetagine-med-rodvin", label: "Lammetagine med rødvin" },
  ],
  "vin-til-oktoberfest-mad": [
    { slug: "wiener-schnitzel-med-hvidvin", label: "Wiener schnitzel med hvidvin" },
  ],
  "vin-til-alsace-mad": [
    { slug: "wiener-schnitzel-med-hvidvin", label: "Wiener schnitzel med hvidvin" },
  ],
  "vin-til-crepes-og-pandekager": [
    { slug: "crepes-suzette-med-hvidvin", label: "Crêpes Suzette med hvidvin" },
  ],
  "vin-til-sommer": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "piknik-sandwich-med-hvidvin-dressing", label: "Piknik-sandwich med hvidvin-dressing" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-piknik": [
    { slug: "piknik-sandwich-med-hvidvin-dressing", label: "Piknik-sandwich med hvidvin-dressing" },
    { slug: "kartoffelsalat-med-hvidvin", label: "Kartoffelsalat med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-haveselskab": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "bedste-sommervin": [
    { slug: "grillet-kylling-med-hvidvin", label: "Grillet kylling med hvidvin" },
    { slug: "kold-pastasalat-med-hvidvin", label: "Kold pastasalat med hvidvin" },
    { slug: "sommerfrugt-i-hvidvin", label: "Sommerfrugt i hvidvin" },
  ],
  "vin-til-grillet-gront": [
    { slug: "ratatouille-med-hvidvin", label: "Ratatouille med hvidvin" },
    { slug: "grillet-halloumi-med-hvidvin", label: "Grillet halloumi med hvidvin" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "hvidvinsbraiserede-porrer", label: "Hvidvinsbraiserede porrer" },
    { slug: "rosenkaal-med-hvidvin-og-oestersauce", label: "Rosenkål med hvidvin og østerssauce" },
    { slug: "hvidvins-urtemarinade-groentsager", label: "Urte-grønt" },
  ],

  "vin-til-ost-og-ostebord": [
    { slug: "portvins-fignemarmelade-med-rosmarin", label: "Portvins-fignemarmelade" },
    { slug: "gorgonzola-creme-med-portvin", label: "Gorgonzola-creme med portvin" },
    { slug: "mini-hvidvinsfondue-tapas", label: "Mini-hvidvinsfondue" },
    { slug: "klar-rodvinsgele-med-vanilje", label: "Klar rødvinsgelé" },
    { slug: "tranebaekompot-grand-marnier-rodvin", label: "Tranebærkompot med Grand Marnier" },
    { slug: "chorizomarmelade-med-sherry", label: "Chorizomarmelade med sherry" },
    { slug: "rabarberkompot-med-rose", label: "Rabarberkompot med rosé" },
  ],

  "vin-til-gedeost": [
    { slug: "rodvinsglaserede-figner-med-gedeost", label: "Rødvinsglaserede figner med gedeost" },
    { slug: "gedeost-crostini-med-skalotteloeg", label: "Gedeost-crostini med skalotteløg" },
  ],

  "vin-til-brie-og-camembert": [
    { slug: "bagt-camembert-med-hvidvin", label: "Bagt camembert med hvidvin" },
  ],

  "vin-til-foie-gras": [
    { slug: "sauternes-gele-med-safran", label: "Sauternes-gelé med safran" },
  ],

  "champagne-til-mad": [
    { slug: "champagne-jordbaersorbet", label: "Champagne-jordbærsorbet" },
    { slug: "hummersuppe-med-cognac-og-bobler", label: "Hummersuppe med cognac og bobler" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med mousserende sabayon" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Mousserende fisk" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "bedste-rosevin": [
    { slug: "dampet-laks-med-rosevinssauce", label: "Dampet laks med rosévinssauce" },
    { slug: "cremet-pastasalat-med-melon-og-parma", label: "Pastasalat med melon og parma" },
  ],
  "portvin-til-ost": [
    { slug: "portvinsglaserede-figner-med-gedeost", label: "Portvinsglaserede figner med gedeost" },
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
    { slug: "figner-i-krydret-portvinssirup", label: "Figner i portvinssirup" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
  ],
  "riesling-til-asiatisk-mad": [
    { slug: "tom-kha-gai-med-hvidvin", label: "Tom Kha Gai med hvidvin" },
    { slug: "gyoza-svinekoed-med-riesling", label: "Gyoza med svinekød" },
    { slug: "sticky-pork-belly-med-shaoxing", label: "Sticky pork belly" },
  ],
  "vin-til-dim-sum": [
    { slug: "gyoza-svinekoed-med-riesling", label: "Gyoza med svinekød" },
  ],
  "vin-til-svampe": [
    { slug: "svampetoast-med-hvidvin-og-timian", label: "Svampetoast med hvidvin" },
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "marsala-svampemarinade", label: "Marsala-porcini" },
    { slug: "cremet-svampesuppe-med-madeira", label: "Cremet svampesuppe med Madeira" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
  ],
  "vin-til-bourgogne-mad": [
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
  ],
  "sadan-bruger-du-vin-til-sauce-og-simren": [
    { slug: "svampe-bourguignon", label: "Svampe Bourguignon" },
    { slug: "balsamico-rodvinsglaserede-skalotteloeg", label: "Glaserede skalotteløg" },
    { slug: "chicken-marsala", label: "Chicken Marsala" },
    { slug: "kanin-i-hvidvin", label: "Kanin i hvidvin" },
    { slug: "hvidvinsbraiseret-fennikel", label: "Hvidvinsbraiseret fennikel" },
    { slug: "hvidvinsbraiserede-porrer", label: "Hvidvinsbraiserede porrer" },
    { slug: "kylling-i-hvidvinssauce-med-porrer-og-vindruer", label: "Kylling med vindruer" },
    { slug: "svinekoteletter-med-sennep-og-hvidvin", label: "Sennep-hvidvinssauce" },
    { slug: "jordskokkesuppe-med-hvidvinsreduktion", label: "Hvidvinsreduktion til suppe" },
    { slug: "klassisk-rodvins-rosmarinmarinade", label: "Rødvinsmarinade" },
    { slug: "bourguignon-marinade", label: "Bourguignon-marinade" },
    { slug: "rodvin-soya-glaze", label: "Rødvins-soya-glaze" },
    { slug: "beurre-blanc", label: "Beurre blanc" },
    { slug: "rodvins-loegkompot", label: "Rødvins-løgkompot" },
    { slug: "sherry-glaseret-svampemix", label: "Sherry-glaseret svampemix" },
    { slug: "balsamico-rodvinssirup-til-steak", label: "Balsamico-rødvinssirup" },
    { slug: "hvidvins-estragonglace-til-kylling", label: "Hvidvins-estragonglace" },
    { slug: "rodvinssirup-med-vanilje", label: "Rødvinssirup med vanilje" },
    { slug: "madeira-glaseret-rosenkaal", label: "Madeira-glaseret rosenkål" },
    { slug: "espresso-marsalasirup", label: "Espresso-Marsalasirup" },
    { slug: "kirsebaersovs-med-portvin", label: "Kirsebærsovs med portvin" },
  ],
  "vin-til-svinekam": [
    { slug: "glaseret-skinke-med-madeirasauce", label: "Glaseret skinke med Madeirasauce" },
    { slug: "hvidvinsmarineret-svinekam", label: "Hvidvinsmarineret svinekam" },
    { slug: "aeble-hvidvinsmarinade", label: "Æble-hvidvinsmarinade" },
  ],
  "bedste-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
    { slug: "portvins-hvidloegsmarinade", label: "Portvins-hvidløgsmarinade" },
    { slug: "portvin-mynte-lammemarinade", label: "Portvin til lam" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
    { slug: "figner-i-krydret-portvinssirup", label: "Figner i portvinssirup" },
  ],
  "hvad-er-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
    { slug: "portvin-mynte-lammemarinade", label: "Port i marinade" },
  ],
  "sadan-serverer-du-portvin": [
    { slug: "kyllingeleverparfait-med-portvinsgele", label: "Kyllingeleverparfait med portvinsgelé" },
  ],
  "vin-til-juleaften": [
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
  ],
  "vin-til-julemad-den-store-guide": [
    { slug: "roedkaal-med-portvin", label: "Rødkål med portvin" },
  ],
  "vin-til-juleand": [
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
  ],
  "pinot-noir-til-and": [
    { slug: "andebryst-med-portvins-og-figneglasering", label: "Andebryst med portvins-figneglasering" },
  ],
  "portvin-til-chokolade": [
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
  ],
  "vin-til-chokolademousse": [
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
  ],
  "bedste-dessertvin": [
    { slug: "moscato-dasti-sorbet", label: "Moscato d'Asti sorbet" },
    { slug: "rodvinskage-med-mork-chokolade", label: "Rødvinskage med mørk chokolade" },
    { slug: "paerer-i-hvidvin-og-safran", label: "Pærer i hvidvin og safran" },
    { slug: "plommetrifli-med-rodvinssirup", label: "Plommetrifli med rødvinssirup" },
    { slug: "hvidvinsgele-med-sommerbaer", label: "Hvidvinsgelé med sommerbær" },
    { slug: "rodvinssorbet-med-brombaer", label: "Rødvinssorbet med brombær" },
    { slug: "tarte-tatin-med-hvidvinskaramel", label: "Tarte Tatin med hvidvinskaramel" },
    { slug: "moscato-pocherede-ferskner", label: "Moscato-pocherede ferskner" },
  ],
  "hvad-er-sherry-vin": [
    { slug: "sherry-trifle", label: "Sherry Trifle" },
    { slug: "sherry-appelsinmarinade", label: "Sherry-appelsinmarinade" },
  ],
  "chardonnay-til-fisk": [
    { slug: "hvidvinsdampet-torsk-en-papillote", label: "Torsk en papillote" },
    { slug: "hummerbisque-med-cognac-og-hvidvin", label: "Hummerbisque" },
    { slug: "hvidvins-safransauce-til-laks", label: "Hvidvins-safransauce til laks" },
  ],
  "vin-til-oksekoed-i-sauce": [
    { slug: "boef-stroganoff-med-rodvin", label: "Boeuf Stroganoff med rødvin" },
    { slug: "portvinssauce-til-oksemoerbrad", label: "Portvinssauce" },
  ],
  "vin-til-vildt": [
    { slug: "vildtgryde-med-portvin-og-enebaer", label: "Vildtgryde med portvin og enebær" },
    { slug: "rodvin-enebaermarinade", label: "Enebærmarinade" },
    { slug: "rodvinssyltede-tyttebaer", label: "Rødvinssyltede tyttebær" },
  ],
  "vin-til-blaaskimmelost": [
    { slug: "gorgonzolasauce-med-hvidvin", label: "Gorgonzolasauce med hvidvin" },
  ],
  "vin-til-baskisk-mad": [
    { slug: "pintxos-txakoli-chorizo", label: "Pintxos med txakoli-chorizo" },
  ],
  "vin-til-japansk-mad": [
    { slug: "kylling-teriyaki-med-sake-og-mirin", label: "Kylling Teriyaki med sake og mirin" },
    { slug: "gyoza-dampet-i-sake", label: "Gyoza dampet i sake" },
    { slug: "klassisk-teriyaki-marinade", label: "Teriyaki" },
    { slug: "sake-misomarinade", label: "Sake-miso" },
  ],
  "bedste-bobler": [
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med sabayon" },
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
  ],
  "bobler-til-fredag": [
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
  ],
  "bobler-champagne-cava-prosecco-og-cremant": [
    { slug: "asparges-med-mousserende-sabayon", label: "Asparges med sabayon" },
    { slug: "loegeringe-i-hvidvinsdej", label: "Løgringe i hvidvinsdej" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Champagne-marinade" },
    { slug: "kir-royal", label: "Kir Royal" },
  ],
  "rosevin-til-grill": [
    { slug: "rose-jordbaermarinade", label: "Jordbærmarinade" },
  ],
  "rosevin-til-mad-og-sommer": [
    { slug: "rose-jordbaermarinade", label: "Rosé-jordbær" },
  ],
  "hvad-er-madeira-vin": [
    { slug: "madeira-allehaandemarinade", label: "Madeira-marinade" },
    { slug: "cremet-svampesuppe-med-madeira", label: "Svampesuppe med Madeira" },
  ],
  "vin-til-lys-fisk": [
    { slug: "hvidvins-dildmarinade", label: "Hvidvin-dild" },
    { slug: "lime-hvidvins-cevichemarinade", label: "Ceviche-marinade" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Bobler til fisk" },
    { slug: "beurre-blanc", label: "Beurre blanc" },
  ],
  "vin-til-grillet-fisk": [
    { slug: "hvidvins-dildmarinade", label: "Grillet laks" },
    { slug: "ingefaer-chili-hvidvinsmarinade", label: "Grillede rejer" },
    { slug: "champagne-mousserende-vinsmarinade", label: "Fast fisk" },
  ],
  "vin-til-vegetariske-og-veganske-retter": [
    { slug: "hvidvins-urtemarinade-groentsager", label: "Grøntsagsmarinade" },
    { slug: "minestrone-di-verdure-med-hvidvin", label: "Minestrone med hvidvin" },
  ],
  "bedste-julevin": [
    { slug: "roedvinsgloegg", label: "Rødvinsgløgg" },
    { slug: "portvinsgloegg", label: "Portvinsgløgg" },
  ],

};
